// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type BulkupdateNPAPublishersResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	PublisherUpgradeProfileBulkResponse *shared.PublisherUpgradeProfileBulkResponse
	// Invalid request
	FourHundred *shared.FourHundred
}

func (b *BulkupdateNPAPublishersResponse) GetContentType() string {
	if b == nil {
		return ""
	}
	return b.ContentType
}

func (b *BulkupdateNPAPublishersResponse) GetStatusCode() int {
	if b == nil {
		return 0
	}
	return b.StatusCode
}

func (b *BulkupdateNPAPublishersResponse) GetRawResponse() *http.Response {
	if b == nil {
		return nil
	}
	return b.RawResponse
}

func (b *BulkupdateNPAPublishersResponse) GetPublisherUpgradeProfileBulkResponse() *shared.PublisherUpgradeProfileBulkResponse {
	if b == nil {
		return nil
	}
	return b.PublisherUpgradeProfileBulkResponse
}

func (b *BulkupdateNPAPublishersResponse) GetFourHundred() *shared.FourHundred {
	if b == nil {
		return nil
	}
	return b.FourHundred
}
