// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type CreateNPALocalBrokerResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	LbrokerResponse *shared.LbrokerResponse
	// Invalid request
	LbrokerResponse400 *shared.LbrokerResponse400
}

func (o *CreateNPALocalBrokerResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateNPALocalBrokerResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateNPALocalBrokerResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateNPALocalBrokerResponse) GetLbrokerResponse() *shared.LbrokerResponse {
	if o == nil {
		return nil
	}
	return o.LbrokerResponse
}

func (o *CreateNPALocalBrokerResponse) GetLbrokerResponse400() *shared.LbrokerResponse400 {
	if o == nil {
		return nil
	}
	return o.LbrokerResponse400
}
