// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type CreateRBACRoleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Role created (hook replaces slim response with full GET result)
	RbacRoleItem *shared.RbacRoleItem
	// Bad request
	RbacRoleErrorResponse *shared.RbacRoleErrorResponse
}

func (c *CreateRBACRoleResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateRBACRoleResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateRBACRoleResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateRBACRoleResponse) GetRbacRoleItem() *shared.RbacRoleItem {
	if c == nil {
		return nil
	}
	return c.RbacRoleItem
}

func (c *CreateRBACRoleResponse) GetRbacRoleErrorResponse() *shared.RbacRoleErrorResponse {
	if c == nil {
		return nil
	}
	return c.RbacRoleErrorResponse
}
