// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type DeleteDeviceClassificationSteeringMappingRequest struct {
	SteeringID int64 `pathParam:"style=simple,explode=false,name=steering_id"`
}

func (d *DeleteDeviceClassificationSteeringMappingRequest) GetSteeringID() int64 {
	if d == nil {
		return 0
	}
	return d.SteeringID
}

type DeleteDeviceClassificationSteeringMappingResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// No mappings found
	DeviceclassificationOnpremErrorResponse *shared.DeviceclassificationOnpremErrorResponse
}

func (d *DeleteDeviceClassificationSteeringMappingResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteDeviceClassificationSteeringMappingResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteDeviceClassificationSteeringMappingResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteDeviceClassificationSteeringMappingResponse) GetDeviceclassificationOnpremErrorResponse() *shared.DeviceclassificationOnpremErrorResponse {
	if d == nil {
		return nil
	}
	return d.DeviceclassificationOnpremErrorResponse
}
