// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type DeleteNPAPrivateAppRequest struct {
	// private apps id
	PrivateAppID int `pathParam:"style=simple,explode=false,name=private_app_id"`
}

func (o *DeleteNPAPrivateAppRequest) GetPrivateAppID() int {
	if o == nil {
		return 0
	}
	return o.PrivateAppID
}

// DeleteNPAPrivateAppResponseBody - successful operation
type DeleteNPAPrivateAppResponseBody struct {
	Status *shared.StatusEnum `json:"status,omitempty"`
}

func (o *DeleteNPAPrivateAppResponseBody) GetStatus() *shared.StatusEnum {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteNPAPrivateAppResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	Object *DeleteNPAPrivateAppResponseBody
	// Invalid request
	PrivateAppsResponse400 *shared.PrivateAppsResponse400
}

func (o *DeleteNPAPrivateAppResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteNPAPrivateAppResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteNPAPrivateAppResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *DeleteNPAPrivateAppResponse) GetObject() *DeleteNPAPrivateAppResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *DeleteNPAPrivateAppResponse) GetPrivateAppsResponse400() *shared.PrivateAppsResponse400 {
	if o == nil {
		return nil
	}
	return o.PrivateAppsResponse400
}
