// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type GetAigAiProviderRequest struct {
	// UUID of the AI provider.
	ProviderID string `pathParam:"style=simple,explode=false,name=provider_id"`
}

func (g *GetAigAiProviderRequest) GetProviderID() string {
	if g == nil {
		return ""
	}
	return g.ProviderID
}

type GetAigAiProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful response.
	AigAiProvider *shared.AigAiProvider
}

func (g *GetAigAiProviderResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetAigAiProviderResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetAigAiProviderResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetAigAiProviderResponse) GetAigAiProvider() *shared.AigAiProvider {
	if g == nil {
		return nil
	}
	return g.AigAiProvider
}
