// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/internal/utils"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type GetCustomCategoryRequest struct {
	// Custom Category UUID
	ID      string `pathParam:"style=simple,explode=false,name=id"`
	Details *bool  `default:"true" queryParam:"style=form,explode=true,name=details"`
}

func (g GetCustomCategoryRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(g, "", false)
}

func (g *GetCustomCategoryRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &g, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (g *GetCustomCategoryRequest) GetID() string {
	if g == nil {
		return ""
	}
	return g.ID
}

func (g *GetCustomCategoryRequest) GetDetails() *bool {
	if g == nil {
		return nil
	}
	return g.Details
}

type GetCustomCategoryResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successfully retrieved Custom Category
	CustomCategoryItem *shared.CustomCategoryItem
	// Not found
	CustomCategoryErrorResponse *shared.CustomCategoryErrorResponse
}

func (g *GetCustomCategoryResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetCustomCategoryResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetCustomCategoryResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetCustomCategoryResponse) GetCustomCategoryItem() *shared.CustomCategoryItem {
	if g == nil {
		return nil
	}
	return g.CustomCategoryItem
}

func (g *GetCustomCategoryResponse) GetCustomCategoryErrorResponse() *shared.CustomCategoryErrorResponse {
	if g == nil {
		return nil
	}
	return g.CustomCategoryErrorResponse
}
