// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type GetIPSecTunnelRequest struct {
	// IPSec tunnel ID
	TunnelID int `pathParam:"style=simple,explode=false,name=tunnel_id"`
}

func (o *GetIPSecTunnelRequest) GetTunnelID() int {
	if o == nil {
		return 0
	}
	return o.TunnelID
}

type GetIPSecTunnelResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	IpsecTunnelGetResponse *shared.IpsecTunnelGetResponse
	// Invalid request
	IpsecResponse400 *shared.IpsecResponse400
}

func (o *GetIPSecTunnelResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetIPSecTunnelResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetIPSecTunnelResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetIPSecTunnelResponse) GetIpsecTunnelGetResponse() *shared.IpsecTunnelGetResponse {
	if o == nil {
		return nil
	}
	return o.IpsecTunnelGetResponse
}

func (o *GetIPSecTunnelResponse) GetIpsecResponse400() *shared.IpsecResponse400 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse400
}
