// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type GetIPSStatusResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	IpsStatusResponse *shared.IpsStatusResponse
}

func (g *GetIPSStatusResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetIPSStatusResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetIPSStatusResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetIPSStatusResponse) GetIpsStatusResponse() *shared.IpsStatusResponse {
	if g == nil {
		return nil
	}
	return g.IpsStatusResponse
}
