// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type GetNPAPolicyInUseRequestBody struct {
	Ids []string `json:"ids,omitempty"`
}

func (o *GetNPAPolicyInUseRequestBody) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}

type Data struct {
	Token *string `json:"token,omitempty"`
}

func (o *Data) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

type ResponseBody struct {
	Data   *Data              `json:"data,omitempty"`
	Status *shared.StatusEnum `json:"status,omitempty"`
}

func (o *ResponseBody) GetData() *Data {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *ResponseBody) GetStatus() *shared.StatusEnum {
	if o == nil {
		return nil
	}
	return o.Status
}

type GetNPAPolicyInUseResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	ResponseBodies []ResponseBody
	// Invalid request
	PrivateAppsResponse400 *shared.PrivateAppsResponse400
}

func (o *GetNPAPolicyInUseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetNPAPolicyInUseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetNPAPolicyInUseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetNPAPolicyInUseResponse) GetResponseBodies() []ResponseBody {
	if o == nil {
		return nil
	}
	return o.ResponseBodies
}

func (o *GetNPAPolicyInUseResponse) GetPrivateAppsResponse400() *shared.PrivateAppsResponse400 {
	if o == nil {
		return nil
	}
	return o.PrivateAppsResponse400
}
