// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/netskope/terraform-provider-ns/internal/sdk/models/shared"
	"net/http"
)

type PatchNPATagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	TagPatchResponse *shared.TagPatchResponse
	// Invalid request
	TagResponse400 *shared.TagResponse400
}

func (o *PatchNPATagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchNPATagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchNPATagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchNPATagsResponse) GetTagPatchResponse() *shared.TagPatchResponse {
	if o == nil {
		return nil
	}
	return o.TagPatchResponse
}

func (o *PatchNPATagsResponse) GetTagResponse400() *shared.TagResponse400 {
	if o == nil {
		return nil
	}
	return o.TagResponse400
}
