// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/models/shared"
	"net/http"
)

type PatchGreTunnelsByIDRequest struct {
	// GRE tunnel id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// GRE tunnel object
	GreTunnelRequestPatch shared.GreTunnelRequestPatch `request:"mediaType=application/json"`
}

func (o *PatchGreTunnelsByIDRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PatchGreTunnelsByIDRequest) GetGreTunnelRequestPatch() shared.GreTunnelRequestPatch {
	if o == nil {
		return shared.GreTunnelRequestPatch{}
	}
	return o.GreTunnelRequestPatch
}

type PatchGreTunnelsByIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	GrePatchResponse200 *shared.GrePatchResponse200
	// Invalid request
	GreResponse400 *shared.GreResponse400
	// Access forbidden
	GreResponse403 *shared.GreResponse403
	// Not found
	GreResponse404 *shared.GreResponse404
	// Method not allowed
	GreResponse405 *shared.GreResponse405
	// Too many requests
	GreResponse429 *shared.GreResponse429
	// Internal server error
	GreResponse500 *shared.GreResponse500
}

func (o *PatchGreTunnelsByIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchGreTunnelsByIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchGreTunnelsByIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PatchGreTunnelsByIDResponse) GetGrePatchResponse200() *shared.GrePatchResponse200 {
	if o == nil {
		return nil
	}
	return o.GrePatchResponse200
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse400() *shared.GreResponse400 {
	if o == nil {
		return nil
	}
	return o.GreResponse400
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse403() *shared.GreResponse403 {
	if o == nil {
		return nil
	}
	return o.GreResponse403
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse404() *shared.GreResponse404 {
	if o == nil {
		return nil
	}
	return o.GreResponse404
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse405() *shared.GreResponse405 {
	if o == nil {
		return nil
	}
	return o.GreResponse405
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse429() *shared.GreResponse429 {
	if o == nil {
		return nil
	}
	return o.GreResponse429
}

func (o *PatchGreTunnelsByIDResponse) GetGreResponse500() *shared.GreResponse500 {
	if o == nil {
		return nil
	}
	return o.GreResponse500
}
