// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/netskope/terraform-provider-ns/internal/sdk/models/shared"
	"net/http"
)

type PutSteeringAppsPrivateTagsStatus string

const (
	PutSteeringAppsPrivateTagsStatusSuccess  PutSteeringAppsPrivateTagsStatus = "success"
	PutSteeringAppsPrivateTagsStatusNotFound PutSteeringAppsPrivateTagsStatus = "not found"
)

func (e PutSteeringAppsPrivateTagsStatus) ToPointer() *PutSteeringAppsPrivateTagsStatus {
	return &e
}
func (e *PutSteeringAppsPrivateTagsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "not found":
		*e = PutSteeringAppsPrivateTagsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PutSteeringAppsPrivateTagsStatus: %v", v)
	}
}

// PutSteeringAppsPrivateTagsResponseBody - successful operation
type PutSteeringAppsPrivateTagsResponseBody struct {
	Data   []shared.TagPrivateAppsResponseAllDetails `json:"data,omitempty"`
	Status *PutSteeringAppsPrivateTagsStatus         `json:"status,omitempty"`
}

func (o *PutSteeringAppsPrivateTagsResponseBody) GetData() []shared.TagPrivateAppsResponseAllDetails {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PutSteeringAppsPrivateTagsResponseBody) GetStatus() *PutSteeringAppsPrivateTagsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type PutSteeringAppsPrivateTagsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	Object *PutSteeringAppsPrivateTagsResponseBody
	// Invalid request
	TagResponse400 *shared.TagResponse400
}

func (o *PutSteeringAppsPrivateTagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutSteeringAppsPrivateTagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutSteeringAppsPrivateTagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutSteeringAppsPrivateTagsResponse) GetObject() *PutSteeringAppsPrivateTagsResponseBody {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *PutSteeringAppsPrivateTagsResponse) GetTagResponse400() *shared.TagResponse400 {
	if o == nil {
		return nil
	}
	return o.TagResponse400
}
