// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type UpdateAigTokenRequest struct {
	// UUID of the token.
	TokenID               string                       `pathParam:"style=simple,explode=false,name=token_id"`
	AigTokenUpdateRequest shared.AigTokenUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAigTokenRequest) GetTokenID() string {
	if u == nil {
		return ""
	}
	return u.TokenID
}

func (u *UpdateAigTokenRequest) GetAigTokenUpdateRequest() shared.AigTokenUpdateRequest {
	if u == nil {
		return shared.AigTokenUpdateRequest{}
	}
	return u.AigTokenUpdateRequest
}

type UpdateAigTokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Token updated successfully.
	AigToken *shared.AigToken
}

func (u *UpdateAigTokenResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAigTokenResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAigTokenResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAigTokenResponse) GetAigToken() *shared.AigToken {
	if u == nil {
		return nil
	}
	return u.AigToken
}
