// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type UpdateAigRateLimitRequest struct {
	// UUID of the rate limit rule.
	RuleID                    string                           `pathParam:"style=simple,explode=false,name=rule_id"`
	AigRateLimitUpdateRequest shared.AigRateLimitUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateAigRateLimitRequest) GetRuleID() string {
	if u == nil {
		return ""
	}
	return u.RuleID
}

func (u *UpdateAigRateLimitRequest) GetAigRateLimitUpdateRequest() shared.AigRateLimitUpdateRequest {
	if u == nil {
		return shared.AigRateLimitUpdateRequest{}
	}
	return u.AigRateLimitUpdateRequest
}

type UpdateAigRateLimitResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Rate limit rule updated successfully.
	AigRateLimit *shared.AigRateLimit
}

func (u *UpdateAigRateLimitResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateAigRateLimitResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateAigRateLimitResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateAigRateLimitResponse) GetAigRateLimit() *shared.AigRateLimit {
	if u == nil {
		return nil
	}
	return u.AigRateLimit
}
