// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
	"net/http"
)

type UpdateDeviceClassificationTagRequest struct {
	// Tag ID
	TagID                                int64                                       `pathParam:"style=simple,explode=false,name=tag_id"`
	DeviceclassificationTagUpdateRequest shared.DeviceclassificationTagUpdateRequest `request:"mediaType=application/json"`
}

func (u *UpdateDeviceClassificationTagRequest) GetTagID() int64 {
	if u == nil {
		return 0
	}
	return u.TagID
}

func (u *UpdateDeviceClassificationTagRequest) GetDeviceclassificationTagUpdateRequest() shared.DeviceclassificationTagUpdateRequest {
	if u == nil {
		return shared.DeviceclassificationTagUpdateRequest{}
	}
	return u.DeviceclassificationTagUpdateRequest
}

type UpdateDeviceClassificationTagResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Tag updated
	DeviceclassificationTagItem *shared.DeviceclassificationTagItem
	// Bad request
	DeviceclassificationTagErrorResponse *shared.DeviceclassificationTagErrorResponse
}

func (u *UpdateDeviceClassificationTagResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateDeviceClassificationTagResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateDeviceClassificationTagResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateDeviceClassificationTagResponse) GetDeviceclassificationTagItem() *shared.DeviceclassificationTagItem {
	if u == nil {
		return nil
	}
	return u.DeviceclassificationTagItem
}

func (u *UpdateDeviceClassificationTagResponse) GetDeviceclassificationTagErrorResponse() *shared.DeviceclassificationTagErrorResponse {
	if u == nil {
		return nil
	}
	return u.DeviceclassificationTagErrorResponse
}
