// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"ns-npa-publisher/internal/sdk/pkg/models/shared"
)

type GetInfrastructurePublishersPublisherIDAppsRequest struct {
	// publisher id
	PublisherID int `pathParam:"style=simple,explode=false,name=publisher_id"`
}

func (o *GetInfrastructurePublishersPublisherIDAppsRequest) GetPublisherID() int {
	if o == nil {
		return 0
	}
	return o.PublisherID
}

type GetInfrastructurePublishersPublisherIDAppsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	PrivateAppsResponse *shared.PrivateAppsResponse
	// Invalid request
	PublishersResponse400 *shared.PublishersResponse400
}

func (o *GetInfrastructurePublishersPublisherIDAppsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetInfrastructurePublishersPublisherIDAppsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetInfrastructurePublishersPublisherIDAppsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetInfrastructurePublishersPublisherIDAppsResponse) GetPrivateAppsResponse() *shared.PrivateAppsResponse {
	if o == nil {
		return nil
	}
	return o.PrivateAppsResponse
}

func (o *GetInfrastructurePublishersPublisherIDAppsResponse) GetPublishersResponse400() *shared.PublishersResponse400 {
	if o == nil {
		return nil
	}
	return o.PublishersResponse400
}
