// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IpsecResponse403 struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *IpsecResponse403) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *IpsecResponse403) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}
