// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// AigAiProviderUpdateRequestSchema - AI API schema the provider exposes.
type AigAiProviderUpdateRequestSchema string

const (
	AigAiProviderUpdateRequestSchemaOpenai AigAiProviderUpdateRequestSchema = "openai"
	AigAiProviderUpdateRequestSchemaGemini AigAiProviderUpdateRequestSchema = "gemini"
	AigAiProviderUpdateRequestSchemaClaude AigAiProviderUpdateRequestSchema = "claude"
)

func (e AigAiProviderUpdateRequestSchema) ToPointer() *AigAiProviderUpdateRequestSchema {
	return &e
}
func (e *AigAiProviderUpdateRequestSchema) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "openai":
		fallthrough
	case "gemini":
		fallthrough
	case "claude":
		*e = AigAiProviderUpdateRequestSchema(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AigAiProviderUpdateRequestSchema: %v", v)
	}
}

// AigAiProviderUpdateRequestProtocol - Connection protocol to the AI backend.
type AigAiProviderUpdateRequestProtocol string

const (
	AigAiProviderUpdateRequestProtocolHTTP        AigAiProviderUpdateRequestProtocol = "http"
	AigAiProviderUpdateRequestProtocolHTTPSSystem AigAiProviderUpdateRequestProtocol = "https-system"
	AigAiProviderUpdateRequestProtocolHTTPSCustom AigAiProviderUpdateRequestProtocol = "https-custom"
	AigAiProviderUpdateRequestProtocolHTTPSSkip   AigAiProviderUpdateRequestProtocol = "https-skip"
)

func (e AigAiProviderUpdateRequestProtocol) ToPointer() *AigAiProviderUpdateRequestProtocol {
	return &e
}
func (e *AigAiProviderUpdateRequestProtocol) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "http":
		fallthrough
	case "https-system":
		fallthrough
	case "https-custom":
		fallthrough
	case "https-skip":
		*e = AigAiProviderUpdateRequestProtocol(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AigAiProviderUpdateRequestProtocol: %v", v)
	}
}

// AigAiProviderUpdateRequest - Request body for updating a custom AI provider. All fields optional.
type AigAiProviderUpdateRequest struct {
	// Updated name for the provider (must still start with `cust-`).
	Name *string `json:"name,omitempty"`
	// AI API schema the provider exposes.
	Schema *AigAiProviderUpdateRequestSchema `json:"schema,omitempty"`
	// Hostname or FQDN of the AI backend.
	Host *string `json:"host,omitempty"`
	// Port number (1–65535).
	Port *int64 `json:"port,omitempty"`
	// Connection protocol to the AI backend.
	Protocol *AigAiProviderUpdateRequestProtocol `json:"protocol,omitempty"`
	// PEM-encoded CA certificate. Required when protocol is `https-custom`.
	// Must be updated together with protocol.
	//
	Certificate *string `json:"certificate,omitempty"`
}

func (a *AigAiProviderUpdateRequest) GetName() *string {
	if a == nil {
		return nil
	}
	return a.Name
}

func (a *AigAiProviderUpdateRequest) GetSchema() *AigAiProviderUpdateRequestSchema {
	if a == nil {
		return nil
	}
	return a.Schema
}

func (a *AigAiProviderUpdateRequest) GetHost() *string {
	if a == nil {
		return nil
	}
	return a.Host
}

func (a *AigAiProviderUpdateRequest) GetPort() *int64 {
	if a == nil {
		return nil
	}
	return a.Port
}

func (a *AigAiProviderUpdateRequest) GetProtocol() *AigAiProviderUpdateRequestProtocol {
	if a == nil {
		return nil
	}
	return a.Protocol
}

func (a *AigAiProviderUpdateRequest) GetCertificate() *string {
	if a == nil {
		return nil
	}
	return a.Certificate
}
