// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/internal/utils"
	"time"
)

// AigApplianceStatus - Registration status of the appliance.
type AigApplianceStatus string

const (
	AigApplianceStatusNotRegistered AigApplianceStatus = "not-registered"
	AigApplianceStatusRegistered    AigApplianceStatus = "registered"
	AigApplianceStatusConnected     AigApplianceStatus = "connected"
	AigApplianceStatusDisconnected  AigApplianceStatus = "disconnected"
)

func (e AigApplianceStatus) ToPointer() *AigApplianceStatus {
	return &e
}
func (e *AigApplianceStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "not-registered":
		fallthrough
	case "registered":
		fallthrough
	case "connected":
		fallthrough
	case "disconnected":
		*e = AigApplianceStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AigApplianceStatus: %v", v)
	}
}

type Partitions struct {
}

type AigApplianceReachability struct {
}

// AigAppliance - Full AI Gateway appliance object as returned by the API.
type AigAppliance struct {
	// Unique identifier for the appliance (used as the Terraform resource ID).
	ID string `json:"id"`
	// Display name for the appliance.
	Name string `json:"name"`
	// Registration status of the appliance.
	Status AigApplianceStatus `json:"status"`
	// Hostname or FQDN of the appliance.
	Host string `json:"host"`
	// HTTP and HTTPS port configuration for the appliance.
	Ports Ports `json:"ports"`
	// List of AI provider IDs associated with this appliance.
	AiProviderIds []string `json:"ai_provider_ids,omitempty"`
	// List of custom MCP server IDs associated with this appliance.
	McpServerIds []string `json:"mcp_server_ids,omitempty"`
	// SKU add-ons (capacity packs) attached to this appliance.
	SkuAddons []SKUAddon `json:"sku_addons,omitempty"`
	// Whether a TLS certificate has been imported onto the appliance.
	CertificateImported *bool `json:"certificate_imported,omitempty"`
	// Expiration time of the imported TLS certificate.
	CertificateExpireTime *time.Time `json:"certificate_expire_time,omitempty"`
	// ID of the upgrade profile assigned to this appliance.
	UpgradeProfileID *string `json:"upgrade_profile_id,omitempty"`
	// IP addresses of the appliance (populated after registration).
	Ips []string `json:"ips,omitempty"`
	// Software version of the appliance.
	Version *string `json:"version,omitempty"`
	// Hypervisor platform the appliance runs on.
	HypervisorPlatform *string `json:"hypervisor_platform,omitempty"`
	// Operating system of the appliance.
	OsName *string `json:"os_name,omitempty"`
	// Uptime in days.
	UptimeDay *int64 `json:"uptime_day,omitempty"`
	// Current CPU utilization percentage.
	CPUUsed *float64 `json:"cpu_used,omitempty"`
	// Historical CPU utilization averages.
	CPUAvg []float64 `json:"cpu_avg,omitempty"`
	// Current memory utilization percentage.
	MemoryUsed *float64 `json:"memory_used,omitempty"`
	// Disk partition information.
	Partitions []Partitions `json:"partitions,omitempty"`
	// Reachability status to Netskope services.
	Reachability []AigApplianceReachability `json:"reachability,omitempty"`
	// Timestamp of the last heartbeat from the appliance.
	HeartbeatTime *time.Time `json:"heartbeat_time,omitempty"`
	// Timestamp when the appliance was created.
	CreateTime *time.Time `json:"create_time,omitempty"`
	// Timestamp when the appliance was last modified.
	ModifyTime *time.Time `json:"modify_time,omitempty"`
	// Timestamp of the last sync with the appliance.
	LastSyncTime *time.Time `json:"last_sync_time,omitempty"`
	// Internal — UI onboarding step tracker.
	UIOnboardingStatus *int64 `json:"ui_onboarding_status,omitempty"`
	// JWT enrollment token returned inline with the create response.
	// Use the `aig_appliance_enrollment_token` resource to generate
	// a fresh token at any time.
	//
	EnrollmentToken *string `json:"enrollment_token,omitempty"`
	// Expiry time of the inline enrollment token from the create response.
	EnrollmentTokenExpireTime *time.Time `json:"enrollment_token_expire_time,omitempty"`
}

func (a AigAppliance) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(a, "", false)
}

func (a *AigAppliance) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &a, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (a *AigAppliance) GetID() string {
	if a == nil {
		return ""
	}
	return a.ID
}

func (a *AigAppliance) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AigAppliance) GetStatus() AigApplianceStatus {
	if a == nil {
		return AigApplianceStatus("")
	}
	return a.Status
}

func (a *AigAppliance) GetHost() string {
	if a == nil {
		return ""
	}
	return a.Host
}

func (a *AigAppliance) GetPorts() Ports {
	if a == nil {
		return Ports{}
	}
	return a.Ports
}

func (a *AigAppliance) GetAiProviderIds() []string {
	if a == nil {
		return nil
	}
	return a.AiProviderIds
}

func (a *AigAppliance) GetMcpServerIds() []string {
	if a == nil {
		return nil
	}
	return a.McpServerIds
}

func (a *AigAppliance) GetSkuAddons() []SKUAddon {
	if a == nil {
		return nil
	}
	return a.SkuAddons
}

func (a *AigAppliance) GetCertificateImported() *bool {
	if a == nil {
		return nil
	}
	return a.CertificateImported
}

func (a *AigAppliance) GetCertificateExpireTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CertificateExpireTime
}

func (a *AigAppliance) GetUpgradeProfileID() *string {
	if a == nil {
		return nil
	}
	return a.UpgradeProfileID
}

func (a *AigAppliance) GetIps() []string {
	if a == nil {
		return nil
	}
	return a.Ips
}

func (a *AigAppliance) GetVersion() *string {
	if a == nil {
		return nil
	}
	return a.Version
}

func (a *AigAppliance) GetHypervisorPlatform() *string {
	if a == nil {
		return nil
	}
	return a.HypervisorPlatform
}

func (a *AigAppliance) GetOsName() *string {
	if a == nil {
		return nil
	}
	return a.OsName
}

func (a *AigAppliance) GetUptimeDay() *int64 {
	if a == nil {
		return nil
	}
	return a.UptimeDay
}

func (a *AigAppliance) GetCPUUsed() *float64 {
	if a == nil {
		return nil
	}
	return a.CPUUsed
}

func (a *AigAppliance) GetCPUAvg() []float64 {
	if a == nil {
		return nil
	}
	return a.CPUAvg
}

func (a *AigAppliance) GetMemoryUsed() *float64 {
	if a == nil {
		return nil
	}
	return a.MemoryUsed
}

func (a *AigAppliance) GetPartitions() []Partitions {
	if a == nil {
		return nil
	}
	return a.Partitions
}

func (a *AigAppliance) GetReachability() []AigApplianceReachability {
	if a == nil {
		return nil
	}
	return a.Reachability
}

func (a *AigAppliance) GetHeartbeatTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.HeartbeatTime
}

func (a *AigAppliance) GetCreateTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.CreateTime
}

func (a *AigAppliance) GetModifyTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.ModifyTime
}

func (a *AigAppliance) GetLastSyncTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.LastSyncTime
}

func (a *AigAppliance) GetUIOnboardingStatus() *int64 {
	if a == nil {
		return nil
	}
	return a.UIOnboardingStatus
}

func (a *AigAppliance) GetEnrollmentToken() *string {
	if a == nil {
		return nil
	}
	return a.EnrollmentToken
}

func (a *AigAppliance) GetEnrollmentTokenExpireTime() *time.Time {
	if a == nil {
		return nil
	}
	return a.EnrollmentTokenExpireTime
}
