// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// AigRateLimitCreateRequest - Request body for creating a rate limit rule.
type AigRateLimitCreateRequest struct {
	// Unique name for the rate limit rule (1–15 characters).
	Name string `json:"name"`
	// Appliance IDs to apply this rule to (max 5).
	// Empty array means the rule applies to all appliances.
	//
	ApplianceIds []string `json:"appliance_ids,omitempty"`
	// Matching criteria for the rate limit rule.
	Criteria AigRateLimitCriteria `json:"criteria"`
	// Rate limit threshold (requests per time unit, per appliance).
	Limit AigRateLimitThreshold `json:"limit"`
	// Custom message returned to clients when the rate limit is exceeded.
	Response *string `json:"response,omitempty"`
}

func (a *AigRateLimitCreateRequest) GetName() string {
	if a == nil {
		return ""
	}
	return a.Name
}

func (a *AigRateLimitCreateRequest) GetApplianceIds() []string {
	if a == nil {
		return nil
	}
	return a.ApplianceIds
}

func (a *AigRateLimitCreateRequest) GetCriteria() AigRateLimitCriteria {
	if a == nil {
		return AigRateLimitCriteria{}
	}
	return a.Criteria
}

func (a *AigRateLimitCreateRequest) GetLimit() AigRateLimitThreshold {
	if a == nil {
		return AigRateLimitThreshold{}
	}
	return a.Limit
}

func (a *AigRateLimitCreateRequest) GetResponse() *string {
	if a == nil {
		return nil
	}
	return a.Response
}
