// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// CciCategoryList - CCI predefined category catalog. Use this data source to resolve category names
// to numeric IDs for use in netskope_custom_category included_predefined_categories.
// Category IDs are tenant-independent (the same ID maps to the same category on all tenants).
type CciCategoryList struct {
	// List of all predefined CCI categories
	Categories []CciCategoryItem `json:"categories,omitempty"`
}

func (c *CciCategoryList) GetCategories() []CciCategoryItem {
	if c == nil {
		return nil
	}
	return c.Categories
}
