// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CustomCategoryUpdateRequest struct {
	// Custom category name (unique per tenant, max 100 characters)
	Name *string `json:"name,omitempty"`
	// Custom category description (max 200 characters)
	Description *string `json:"description,omitempty"`
	// Numeric string IDs of predefined Netskope categories to include (e.g. "500")
	IncludedPredefinedCategories []string `json:"included_predefined_categories,omitempty"`
	// Numeric string IDs of URL lists to include (e.g. "22")
	IncludedURLLists []string `json:"included_url_lists,omitempty"`
	// Numeric string IDs of URL lists to exclude (e.g. "19")
	ExcludedURLLists []string `json:"excluded_url_lists,omitempty"`
	// UUIDs of destination profiles to include
	IncludedDestinationProfiles []string `json:"included_destination_profiles,omitempty"`
	// UUIDs of destination profiles to exclude
	ExcludedDestinationProfiles []string `json:"excluded_destination_profiles,omitempty"`
}

func (c *CustomCategoryUpdateRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CustomCategoryUpdateRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}

func (c *CustomCategoryUpdateRequest) GetIncludedPredefinedCategories() []string {
	if c == nil {
		return nil
	}
	return c.IncludedPredefinedCategories
}

func (c *CustomCategoryUpdateRequest) GetIncludedURLLists() []string {
	if c == nil {
		return nil
	}
	return c.IncludedURLLists
}

func (c *CustomCategoryUpdateRequest) GetExcludedURLLists() []string {
	if c == nil {
		return nil
	}
	return c.ExcludedURLLists
}

func (c *CustomCategoryUpdateRequest) GetIncludedDestinationProfiles() []string {
	if c == nil {
		return nil
	}
	return c.IncludedDestinationProfiles
}

func (c *CustomCategoryUpdateRequest) GetExcludedDestinationProfiles() []string {
	if c == nil {
		return nil
	}
	return c.ExcludedDestinationProfiles
}
