// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeviceTagUpdateRequest struct {
	// Tag name
	Name *string `json:"name,omitempty"`
	// Tag description
	Description *string `json:"description,omitempty"`
}

func (d *DeviceTagUpdateRequest) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DeviceTagUpdateRequest) GetDescription() *string {
	if d == nil {
		return nil
	}
	return d.Description
}
