// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type DeviceclassificationOnpremErrorResponse struct {
	StatusCode *int64  `json:"statusCode,omitempty"`
	Message    *string `json:"message,omitempty"`
	Error      *string `json:"error,omitempty"`
}

func (d *DeviceclassificationOnpremErrorResponse) GetStatusCode() *int64 {
	if d == nil {
		return nil
	}
	return d.StatusCode
}

func (d *DeviceclassificationOnpremErrorResponse) GetMessage() *string {
	if d == nil {
		return nil
	}
	return d.Message
}

func (d *DeviceclassificationOnpremErrorResponse) GetError() *string {
	if d == nil {
		return nil
	}
	return d.Error
}
