// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Os - Operating system this rule applies to
type Os string

const (
	OsWindows  Os = "windows"
	OsMac      Os = "mac"
	OsAndroid  Os = "android"
	OsIos      Os = "ios"
	OsChromeos Os = "chromeos"
	OsLinux    Os = "linux"
)

func (e Os) ToPointer() *Os {
	return &e
}
func (e *Os) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "windows":
		fallthrough
	case "mac":
		fallthrough
	case "android":
		fallthrough
	case "ios":
		fallthrough
	case "chromeos":
		fallthrough
	case "linux":
		*e = Os(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Os: %v", v)
	}
}

type DeviceclassificationRuleItem struct {
	// Rule ID
	RuleID *int64 `json:"id,omitempty"`
	// Rule name (unique within its label)
	Name *string `json:"name,omitempty"`
	// Label (tag) name this rule belongs to
	Label *string `json:"label,omitempty"`
	// Operating system this rule applies to
	Os *Os `json:"os,omitempty"`
	// Nested boolean condition tree. Structure uses $and/$or operators containing check nodes (e.g. min_os_version_check, av_check, file_check, domain_check). Checks must appear at the fourth level or deeper (minimum: $and > $and > $or > check).
	//
	Conditions any `json:"conditions,omitempty"`
	// Email of the user who last modified this rule
	ModifiedBy *string `json:"modifiedBy,omitempty"`
	// Last modification timestamp (ISO 8601)
	ModifiedTime *string `json:"modifiedTime,omitempty"`
}

func (d *DeviceclassificationRuleItem) GetRuleID() *int64 {
	if d == nil {
		return nil
	}
	return d.RuleID
}

func (d *DeviceclassificationRuleItem) GetName() *string {
	if d == nil {
		return nil
	}
	return d.Name
}

func (d *DeviceclassificationRuleItem) GetLabel() *string {
	if d == nil {
		return nil
	}
	return d.Label
}

func (d *DeviceclassificationRuleItem) GetOs() *Os {
	if d == nil {
		return nil
	}
	return d.Os
}

func (d *DeviceclassificationRuleItem) GetConditions() any {
	if d == nil {
		return nil
	}
	return d.Conditions
}

func (d *DeviceclassificationRuleItem) GetModifiedBy() *string {
	if d == nil {
		return nil
	}
	return d.ModifiedBy
}

func (d *DeviceclassificationRuleItem) GetModifiedTime() *string {
	if d == nil {
		return nil
	}
	return d.ModifiedTime
}
