// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/internal/utils"
	"time"
)

// EnrollmentTokenResponse - JWT enrollment token for appliance registration.
type EnrollmentTokenResponse struct {
	// JWT token used to enroll/register the appliance with the Netskope
	// tenant. Valid for 24 hours from generation.
	//
	EnrollmentToken string `json:"enrollment_token"`
	// Token expiration timestamp (24 hours from creation).
	ExpireTime time.Time `json:"expire_time"`
}

func (e EnrollmentTokenResponse) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(e, "", false)
}

func (e *EnrollmentTokenResponse) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &e, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (e *EnrollmentTokenResponse) GetEnrollmentToken() string {
	if e == nil {
		return ""
	}
	return e.EnrollmentToken
}

func (e *EnrollmentTokenResponse) GetExpireTime() time.Time {
	if e == nil {
		return time.Time{}
	}
	return e.ExpireTime
}
