// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type GreTunnelRequestPostXff struct {
	Enable *bool    `json:"enable,omitempty"`
	Iplist []string `json:"iplist,omitempty"`
}

func (o *GreTunnelRequestPostXff) GetEnable() *bool {
	if o == nil {
		return nil
	}
	return o.Enable
}

func (o *GreTunnelRequestPostXff) GetIplist() []string {
	if o == nil {
		return nil
	}
	return o.Iplist
}

type GreTunnelRequestPostOptions struct {
	Xff *GreTunnelRequestPostXff `json:"xff,omitempty"`
}

func (o *GreTunnelRequestPostOptions) GetXff() *GreTunnelRequestPostXff {
	if o == nil {
		return nil
	}
	return o.Xff
}

type GreTunnelRequestPost struct {
	Enable        *bool                        `json:"enable,omitempty"`
	Notes         *string                      `json:"notes,omitempty"`
	Options       *GreTunnelRequestPostOptions `json:"options,omitempty"`
	Pops          []string                     `json:"pops,omitempty"`
	Site          *string                      `json:"site,omitempty"`
	Sourcetype    *string                      `json:"sourcetype,omitempty"`
	Srcipidentity *string                      `json:"srcipidentity,omitempty"`
	Template      *string                      `json:"template,omitempty"`
	Vendor        *string                      `json:"vendor,omitempty"`
}

func (o *GreTunnelRequestPost) GetEnable() *bool {
	if o == nil {
		return nil
	}
	return o.Enable
}

func (o *GreTunnelRequestPost) GetNotes() *string {
	if o == nil {
		return nil
	}
	return o.Notes
}

func (o *GreTunnelRequestPost) GetOptions() *GreTunnelRequestPostOptions {
	if o == nil {
		return nil
	}
	return o.Options
}

func (o *GreTunnelRequestPost) GetPops() []string {
	if o == nil {
		return nil
	}
	return o.Pops
}

func (o *GreTunnelRequestPost) GetSite() *string {
	if o == nil {
		return nil
	}
	return o.Site
}

func (o *GreTunnelRequestPost) GetSourcetype() *string {
	if o == nil {
		return nil
	}
	return o.Sourcetype
}

func (o *GreTunnelRequestPost) GetSrcipidentity() *string {
	if o == nil {
		return nil
	}
	return o.Srcipidentity
}

func (o *GreTunnelRequestPost) GetTemplate() *string {
	if o == nil {
		return nil
	}
	return o.Template
}

func (o *GreTunnelRequestPost) GetVendor() *string {
	if o == nil {
		return nil
	}
	return o.Vendor
}
