// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GreTunnelCreateResponse struct {
	Data   []GreTunnelItem `json:"data,omitempty"`
	Result *string         `json:"result,omitempty"`
	Status *int64          `json:"status,omitempty"`
}

func (g *GreTunnelCreateResponse) GetData() []GreTunnelItem {
	if g == nil {
		return nil
	}
	return g.Data
}

func (g *GreTunnelCreateResponse) GetResult() *string {
	if g == nil {
		return nil
	}
	return g.Result
}

func (g *GreTunnelCreateResponse) GetStatus() *int64 {
	if g == nil {
		return nil
	}
	return g.Status
}
