// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type IpsecTunnelPopResultItem struct {
	Gateway    *string `json:"gateway,omitempty"`
	Name       *string `json:"name,omitempty"`
	Primary    *bool   `json:"primary,omitempty"`
	Probeip    *string `json:"probeip,omitempty"`
	Since      *string `json:"since,omitempty"`
	Status     *string `json:"status,omitempty"`
	Throughput *string `json:"throughput,omitempty"`
}

func (o *IpsecTunnelPopResultItem) GetGateway() *string {
	if o == nil {
		return nil
	}
	return o.Gateway
}

func (o *IpsecTunnelPopResultItem) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *IpsecTunnelPopResultItem) GetPrimary() *bool {
	if o == nil {
		return nil
	}
	return o.Primary
}

func (o *IpsecTunnelPopResultItem) GetProbeip() *string {
	if o == nil {
		return nil
	}
	return o.Probeip
}

func (o *IpsecTunnelPopResultItem) GetSince() *string {
	if o == nil {
		return nil
	}
	return o.Since
}

func (o *IpsecTunnelPopResultItem) GetStatus() *string {
	if o == nil {
		return nil
	}
	return o.Status
}

func (o *IpsecTunnelPopResultItem) GetThroughput() *string {
	if o == nil {
		return nil
	}
	return o.Throughput
}
