// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/internal/utils"
)

// LbrokerPostRequestAccessViaPublicIP - Controls access to LBR via public IP
type LbrokerPostRequestAccessViaPublicIP string

const (
	LbrokerPostRequestAccessViaPublicIPNone      LbrokerPostRequestAccessViaPublicIP = "NONE"
	LbrokerPostRequestAccessViaPublicIPOffPrem   LbrokerPostRequestAccessViaPublicIP = "OFF_PREM"
	LbrokerPostRequestAccessViaPublicIPOnPrem    LbrokerPostRequestAccessViaPublicIP = "ON_PREM"
	LbrokerPostRequestAccessViaPublicIPOnOffPrem LbrokerPostRequestAccessViaPublicIP = "ON_OFF_PREM"
)

func (e LbrokerPostRequestAccessViaPublicIP) ToPointer() *LbrokerPostRequestAccessViaPublicIP {
	return &e
}
func (e *LbrokerPostRequestAccessViaPublicIP) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "NONE":
		fallthrough
	case "OFF_PREM":
		fallthrough
	case "ON_PREM":
		fallthrough
	case "ON_OFF_PREM":
		*e = LbrokerPostRequestAccessViaPublicIP(v)
		return nil
	default:
		return fmt.Errorf("invalid value for LbrokerPostRequestAccessViaPublicIP: %v", v)
	}
}

type LbrokerPostRequest struct {
	LocalBrokerName *string `json:"name,omitempty"`
	CityName        *string `json:"city_name,omitempty"`
	RegionName      *string `json:"region_name,omitempty"`
	CountryName     *string `json:"country_name,omitempty"`
	CountryCode     *string `json:"country_code,omitempty"`
	// Latitude in decimal degrees
	Latitude *float32 `json:"latitude,omitempty"`
	// Longitude in decimal degrees
	Longitude *float32 `json:"longitude,omitempty"`
	// Public IP address of the local broker
	CustomPublicIP *string `json:"custom_public_ip,omitempty"`
	// Private IP address of the local broker
	CustomPrivateIP *string `json:"custom_private_ip,omitempty"`
	// Controls access to LBR via public IP
	AccessViaPublicIP *LbrokerPostRequestAccessViaPublicIP `default:"NONE" json:"access_via_public_ip"`
	// Array of label UUIDs to associate with the local broker
	LabelIds []string `json:"label_ids,omitempty"`
}

func (l LbrokerPostRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *LbrokerPostRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (l *LbrokerPostRequest) GetLocalBrokerName() *string {
	if l == nil {
		return nil
	}
	return l.LocalBrokerName
}

func (l *LbrokerPostRequest) GetCityName() *string {
	if l == nil {
		return nil
	}
	return l.CityName
}

func (l *LbrokerPostRequest) GetRegionName() *string {
	if l == nil {
		return nil
	}
	return l.RegionName
}

func (l *LbrokerPostRequest) GetCountryName() *string {
	if l == nil {
		return nil
	}
	return l.CountryName
}

func (l *LbrokerPostRequest) GetCountryCode() *string {
	if l == nil {
		return nil
	}
	return l.CountryCode
}

func (l *LbrokerPostRequest) GetLatitude() *float32 {
	if l == nil {
		return nil
	}
	return l.Latitude
}

func (l *LbrokerPostRequest) GetLongitude() *float32 {
	if l == nil {
		return nil
	}
	return l.Longitude
}

func (l *LbrokerPostRequest) GetCustomPublicIP() *string {
	if l == nil {
		return nil
	}
	return l.CustomPublicIP
}

func (l *LbrokerPostRequest) GetCustomPrivateIP() *string {
	if l == nil {
		return nil
	}
	return l.CustomPrivateIP
}

func (l *LbrokerPostRequest) GetAccessViaPublicIP() *LbrokerPostRequestAccessViaPublicIP {
	if l == nil {
		return nil
	}
	return l.AccessViaPublicIP
}

func (l *LbrokerPostRequest) GetLabelIds() []string {
	if l == nil {
		return nil
	}
	return l.LabelIds
}
