// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type NpaPolicyResponseItemTestMatchCriteriaAction struct {
	ActionName *string `json:"action_name,omitempty"`
}

func (o *NpaPolicyResponseItemTestMatchCriteriaAction) GetActionName() *string {
	if o == nil {
		return nil
	}
	return o.ActionName
}

type NpaPolicyResponseItemTestActivities struct {
	Activity          *string  `json:"activity,omitempty"`
	ListOfConstraints []string `json:"list_of_constraints,omitempty"`
}

func (o *NpaPolicyResponseItemTestActivities) GetActivity() *string {
	if o == nil {
		return nil
	}
	return o.Activity
}

func (o *NpaPolicyResponseItemTestActivities) GetListOfConstraints() []string {
	if o == nil {
		return nil
	}
	return o.ListOfConstraints
}

type NpaPolicyResponseItemTestPrivateAppsWithActivities struct {
	Activities []NpaPolicyResponseItemTestActivities `json:"activities,omitempty"`
	AppID      []string                              `json:"appId,omitempty"`
	AppName    *string                               `json:"appName,omitempty"`
}

func (o *NpaPolicyResponseItemTestPrivateAppsWithActivities) GetActivities() []NpaPolicyResponseItemTestActivities {
	if o == nil {
		return nil
	}
	return o.Activities
}

func (o *NpaPolicyResponseItemTestPrivateAppsWithActivities) GetAppID() []string {
	if o == nil {
		return nil
	}
	return o.AppID
}

func (o *NpaPolicyResponseItemTestPrivateAppsWithActivities) GetAppName() *string {
	if o == nil {
		return nil
	}
	return o.AppName
}

type RuleData struct {
	AccessMethod              []string                                             `json:"access_method,omitempty"`
	ExternalDlp               *bool                                                `json:"external_dlp,omitempty"`
	JSONVersion               *float64                                             `json:"json_version,omitempty"`
	MatchCriteriaAction       *NpaPolicyResponseItemTestMatchCriteriaAction        `json:"match_criteria_action,omitempty"`
	PolicyType                *string                                              `json:"policy_type,omitempty"`
	PrivateApps               []string                                             `json:"privateApps,omitempty"`
	PrivateAppsWithActivities []NpaPolicyResponseItemTestPrivateAppsWithActivities `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *bool                                                `json:"show_dlp_profile_action_table,omitempty"`
	UserType                  *string                                              `json:"userType,omitempty"`
	Version                   *float64                                             `json:"version,omitempty"`
}

func (o *RuleData) GetAccessMethod() []string {
	if o == nil {
		return nil
	}
	return o.AccessMethod
}

func (o *RuleData) GetExternalDlp() *bool {
	if o == nil {
		return nil
	}
	return o.ExternalDlp
}

func (o *RuleData) GetJSONVersion() *float64 {
	if o == nil {
		return nil
	}
	return o.JSONVersion
}

func (o *RuleData) GetMatchCriteriaAction() *NpaPolicyResponseItemTestMatchCriteriaAction {
	if o == nil {
		return nil
	}
	return o.MatchCriteriaAction
}

func (o *RuleData) GetPolicyType() *string {
	if o == nil {
		return nil
	}
	return o.PolicyType
}

func (o *RuleData) GetPrivateApps() []string {
	if o == nil {
		return nil
	}
	return o.PrivateApps
}

func (o *RuleData) GetPrivateAppsWithActivities() []NpaPolicyResponseItemTestPrivateAppsWithActivities {
	if o == nil {
		return nil
	}
	return o.PrivateAppsWithActivities
}

func (o *RuleData) GetShowDlpProfileActionTable() *bool {
	if o == nil {
		return nil
	}
	return o.ShowDlpProfileActionTable
}

func (o *RuleData) GetUserType() *string {
	if o == nil {
		return nil
	}
	return o.UserType
}

func (o *RuleData) GetVersion() *float64 {
	if o == nil {
		return nil
	}
	return o.Version
}

type NpaPolicyResponseItemTest struct {
	Enabled    *string   `json:"enabled,omitempty"`
	ModifyBy   *string   `json:"modify_by,omitempty"`
	ModifyTime *string   `json:"modify_time,omitempty"`
	ModifyType *string   `json:"modify_type,omitempty"`
	PolicyType *string   `json:"policy_type,omitempty"`
	RuleData   *RuleData `json:"rule_data,omitempty"`
	RuleID     *string   `json:"rule_id,omitempty"`
	RuleName   *string   `json:"rule_name,omitempty"`
}

func (o *NpaPolicyResponseItemTest) GetEnabled() *string {
	if o == nil {
		return nil
	}
	return o.Enabled
}

func (o *NpaPolicyResponseItemTest) GetModifyBy() *string {
	if o == nil {
		return nil
	}
	return o.ModifyBy
}

func (o *NpaPolicyResponseItemTest) GetModifyTime() *string {
	if o == nil {
		return nil
	}
	return o.ModifyTime
}

func (o *NpaPolicyResponseItemTest) GetModifyType() *string {
	if o == nil {
		return nil
	}
	return o.ModifyType
}

func (o *NpaPolicyResponseItemTest) GetPolicyType() *string {
	if o == nil {
		return nil
	}
	return o.PolicyType
}

func (o *NpaPolicyResponseItemTest) GetRuleData() *RuleData {
	if o == nil {
		return nil
	}
	return o.RuleData
}

func (o *NpaPolicyResponseItemTest) GetRuleID() *string {
	if o == nil {
		return nil
	}
	return o.RuleID
}

func (o *NpaPolicyResponseItemTest) GetRuleName() *string {
	if o == nil {
		return nil
	}
	return o.RuleName
}
