// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/internal/utils"
)

type AccessMethod string

const (
	AccessMethodClient            AccessMethod = "Client"
	AccessMethodClientless        AccessMethod = "Clientless"
	AccessMethodEnterpriseBrowser AccessMethod = "Enterprise Browser"
)

func (e AccessMethod) ToPointer() *AccessMethod {
	return &e
}
func (e *AccessMethod) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "Client":
		fallthrough
	case "Clientless":
		fallthrough
	case "Enterprise Browser":
		*e = AccessMethod(v)
		return nil
	default:
		return fmt.Errorf("invalid value for AccessMethod: %v", v)
	}
}

type ActionName string

const (
	ActionNameAllow ActionName = "allow"
	ActionNameBlock ActionName = "block"
)

func (e ActionName) ToPointer() *ActionName {
	return &e
}
func (e *ActionName) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "allow":
		fallthrough
	case "block":
		*e = ActionName(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ActionName: %v", v)
	}
}

type MatchCriteriaAction struct {
	ActionName *ActionName `json:"action_name,omitempty"`
	// Whether to emit an alert when the rule matches (required for block action)
	EmitAlert *bool `json:"emit_alert,omitempty"`
	// Notification template name (required for block action). Use the display name (e.g. "Default Template"), not the file name.
	Template *string `json:"template,omitempty"`
}

func (m *MatchCriteriaAction) GetActionName() *ActionName {
	if m == nil {
		return nil
	}
	return m.ActionName
}

func (m *MatchCriteriaAction) GetEmitAlert() *bool {
	if m == nil {
		return nil
	}
	return m.EmitAlert
}

func (m *MatchCriteriaAction) GetTemplate() *string {
	if m == nil {
		return nil
	}
	return m.Template
}

type PolicyType string

const (
	PolicyTypePrivateApp PolicyType = "private-app"
)

func (e PolicyType) ToPointer() *PolicyType {
	return &e
}
func (e *PolicyType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "private-app":
		*e = PolicyType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PolicyType: %v", v)
	}
}

type UserType string

const (
	UserTypeUser UserType = "user"
)

func (e UserType) ToPointer() *UserType {
	return &e
}
func (e *UserType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "user":
		*e = UserType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for UserType: %v", v)
	}
}

type Activity string

const (
	ActivityAny Activity = "any"
)

func (e Activity) ToPointer() *Activity {
	return &e
}
func (e *Activity) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "any":
		*e = Activity(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Activity: %v", v)
	}
}

type Activities struct {
	Activity          *Activity `json:"activity,omitempty"`
	ListOfConstraints []string  `json:"list_of_constraints,omitempty"`
}

func (a *Activities) GetActivity() *Activity {
	if a == nil {
		return nil
	}
	return a.Activity
}

func (a *Activities) GetListOfConstraints() []string {
	if a == nil {
		return nil
	}
	return a.ListOfConstraints
}

type PrivateAppsWithActivities struct {
	AppName    *string      `json:"appName,omitempty"`
	Activities []Activities `json:"activities,omitempty"`
}

func (p *PrivateAppsWithActivities) GetAppName() *string {
	if p == nil {
		return nil
	}
	return p.AppName
}

func (p *PrivateAppsWithActivities) GetActivities() []Activities {
	if p == nil {
		return nil
	}
	return p.Activities
}

type NpaPolicyRuleData struct {
	AccessMethod              []AccessMethod               `json:"access_method,omitempty"`
	BNegateNetLocation        *bool                        `default:"false" json:"b_negateNetLocation"`
	BNegateSrcCountries       *bool                        `default:"false" json:"b_negateSrcCountries"`
	Classification            []string                     `json:"classification,omitempty"`
	PeriodicReauth            *NpaPolicyRulePeriodicReauth `json:"periodic_reauth,omitempty"`
	JSONVersion               *int64                       `default:"3" json:"json_version"`
	DeviceClassificationID    []string                     `json:"device_classification_id,omitempty"`
	MatchCriteriaAction       *MatchCriteriaAction         `json:"match_criteria_action,omitempty"`
	NetLocationObj            []string                     `json:"net_location_obj,omitempty"`
	OrganizationUnits         []string                     `json:"organization_units,omitempty"`
	PolicyType                *PolicyType                  `default:"private-app" json:"policy_type"`
	PrivateAppTagIds          []string                     `json:"privateAppTagIds,omitempty"`
	PrivateAppTags            []string                     `json:"privateAppTags,omitempty"`
	PrivateApps               []string                     `json:"privateApps,omitempty"`
	SrcCountries              []string                     `json:"srcCountries,omitempty"`
	UserGroups                []string                     `json:"userGroups,omitempty"`
	UserType                  *UserType                    `json:"userType,omitempty"`
	Users                     []string                     `json:"users,omitempty"`
	Version                   *int64                       `json:"version,omitempty"`
	DlpActions                []NpaPolicyRuleDlp           `json:"dlp_actions,omitempty"`
	TssActions                []NpaPolicyRuleTss           `json:"tss_actions,omitempty"`
	TssProfile                []string                     `json:"tss_profile,omitempty"`
	ExternalDlp               *bool                        `default:"false" json:"external_dlp"`
	PrivateAppsWithActivities []PrivateAppsWithActivities  `json:"privateAppsWithActivities,omitempty"`
	ShowDlpProfileActionTable *bool                        `default:"false" json:"show_dlp_profile_action_table"`
	// Schedule configuration for policy enforcement timing
	Schedule *NpaSchedule `json:"schedule,omitempty"`
}

func (n NpaPolicyRuleData) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(n, "", false)
}

func (n *NpaPolicyRuleData) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &n, "", false, nil); err != nil {
		return err
	}
	return nil
}

func (n *NpaPolicyRuleData) GetAccessMethod() []AccessMethod {
	if n == nil {
		return nil
	}
	return n.AccessMethod
}

func (n *NpaPolicyRuleData) GetBNegateNetLocation() *bool {
	if n == nil {
		return nil
	}
	return n.BNegateNetLocation
}

func (n *NpaPolicyRuleData) GetBNegateSrcCountries() *bool {
	if n == nil {
		return nil
	}
	return n.BNegateSrcCountries
}

func (n *NpaPolicyRuleData) GetClassification() []string {
	if n == nil {
		return nil
	}
	return n.Classification
}

func (n *NpaPolicyRuleData) GetPeriodicReauth() *NpaPolicyRulePeriodicReauth {
	if n == nil {
		return nil
	}
	return n.PeriodicReauth
}

func (n *NpaPolicyRuleData) GetJSONVersion() *int64 {
	if n == nil {
		return nil
	}
	return n.JSONVersion
}

func (n *NpaPolicyRuleData) GetDeviceClassificationID() []string {
	if n == nil {
		return nil
	}
	return n.DeviceClassificationID
}

func (n *NpaPolicyRuleData) GetMatchCriteriaAction() *MatchCriteriaAction {
	if n == nil {
		return nil
	}
	return n.MatchCriteriaAction
}

func (n *NpaPolicyRuleData) GetNetLocationObj() []string {
	if n == nil {
		return nil
	}
	return n.NetLocationObj
}

func (n *NpaPolicyRuleData) GetOrganizationUnits() []string {
	if n == nil {
		return nil
	}
	return n.OrganizationUnits
}

func (n *NpaPolicyRuleData) GetPolicyType() *PolicyType {
	if n == nil {
		return nil
	}
	return n.PolicyType
}

func (n *NpaPolicyRuleData) GetPrivateAppTagIds() []string {
	if n == nil {
		return nil
	}
	return n.PrivateAppTagIds
}

func (n *NpaPolicyRuleData) GetPrivateAppTags() []string {
	if n == nil {
		return nil
	}
	return n.PrivateAppTags
}

func (n *NpaPolicyRuleData) GetPrivateApps() []string {
	if n == nil {
		return nil
	}
	return n.PrivateApps
}

func (n *NpaPolicyRuleData) GetSrcCountries() []string {
	if n == nil {
		return nil
	}
	return n.SrcCountries
}

func (n *NpaPolicyRuleData) GetUserGroups() []string {
	if n == nil {
		return nil
	}
	return n.UserGroups
}

func (n *NpaPolicyRuleData) GetUserType() *UserType {
	if n == nil {
		return nil
	}
	return n.UserType
}

func (n *NpaPolicyRuleData) GetUsers() []string {
	if n == nil {
		return nil
	}
	return n.Users
}

func (n *NpaPolicyRuleData) GetVersion() *int64 {
	if n == nil {
		return nil
	}
	return n.Version
}

func (n *NpaPolicyRuleData) GetDlpActions() []NpaPolicyRuleDlp {
	if n == nil {
		return nil
	}
	return n.DlpActions
}

func (n *NpaPolicyRuleData) GetTssActions() []NpaPolicyRuleTss {
	if n == nil {
		return nil
	}
	return n.TssActions
}

func (n *NpaPolicyRuleData) GetTssProfile() []string {
	if n == nil {
		return nil
	}
	return n.TssProfile
}

func (n *NpaPolicyRuleData) GetExternalDlp() *bool {
	if n == nil {
		return nil
	}
	return n.ExternalDlp
}

func (n *NpaPolicyRuleData) GetPrivateAppsWithActivities() []PrivateAppsWithActivities {
	if n == nil {
		return nil
	}
	return n.PrivateAppsWithActivities
}

func (n *NpaPolicyRuleData) GetShowDlpProfileActionTable() *bool {
	if n == nil {
		return nil
	}
	return n.ShowDlpProfileActionTable
}

func (n *NpaPolicyRuleData) GetSchedule() *NpaSchedule {
	if n == nil {
		return nil
	}
	return n.Schedule
}
