// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PrivateAppsPostResponseAppOption struct {
}

type PrivateAppsPostResponseReachability struct {
	ErrorCode   *int64  `json:"error_code,omitempty"`
	ErrorString *string `json:"error_string,omitempty"`
	Reachable   *bool   `json:"reachable,omitempty"`
}

func (p *PrivateAppsPostResponseReachability) GetErrorCode() *int64 {
	if p == nil {
		return nil
	}
	return p.ErrorCode
}

func (p *PrivateAppsPostResponseReachability) GetErrorString() *string {
	if p == nil {
		return nil
	}
	return p.ErrorString
}

func (p *PrivateAppsPostResponseReachability) GetReachable() *bool {
	if p == nil {
		return nil
	}
	return p.Reachable
}

type PrivateAppsPostResponseTags struct {
	TagID   *int    `json:"tag_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
}

func (p *PrivateAppsPostResponseTags) GetTagID() *int {
	if p == nil {
		return nil
	}
	return p.TagID
}

func (p *PrivateAppsPostResponseTags) GetTagName() *string {
	if p == nil {
		return nil
	}
	return p.TagName
}

type PrivateAppsPostResponseData struct {
	AllowUnauthenticatedCors    *bool                                `json:"allow_unauthenticated_cors,omitempty"`
	AllowURIBypass              *bool                                `json:"allow_uri_bypass,omitempty"`
	AppID                       *int                                 `json:"app_id,omitempty"`
	PrivateAppName              *string                              `json:"app_name,omitempty"`
	AppOption                   *PrivateAppsPostResponseAppOption    `json:"app_option,omitempty"`
	BypassUris                  []string                             `json:"bypass_uris,omitempty"`
	ClientlessAccess            *bool                                `json:"clientless_access,omitempty"`
	PrivateAppHostname          *string                              `json:"host,omitempty"`
	PrivateAppID                *int                                 `json:"id,omitempty"`
	IsUserPortalApp             *bool                                `json:"is_user_portal_app,omitempty"`
	ModifiedBy                  *string                              `json:"modified_by,omitempty"`
	ModifyTime                  *string                              `json:"modify_time,omitempty"`
	Name                        *string                              `json:"name,omitempty"`
	Policies                    []string                             `json:"policies,omitempty"`
	PrivateAppProtocol          *string                              `json:"private_app_protocol,omitempty"`
	Protocols                   []ProtocolItem                       `json:"protocols,omitempty"`
	PublicHost                  *string                              `json:"public_host,omitempty"`
	Reachability                *PrivateAppsPostResponseReachability `json:"reachability,omitempty"`
	RealHost                    *string                              `json:"real_host,omitempty"`
	ServicePublisherAssignments []ServicePublisherAssignmentItem     `json:"service_publisher_assignments,omitempty"`
	SteeringConfigs             []string                             `json:"steering_configs,omitempty"`
	SupplementDNSForOsx         *bool                                `json:"supplement_dns_for_osx,omitempty"`
	Tags                        []PrivateAppsPostResponseTags        `json:"tags,omitempty"`
	TrustSelfSignedCerts        *bool                                `json:"trust_self_signed_certs,omitempty"`
	UribypassHeaderValue        *string                              `json:"uribypass_header_value,omitempty"`
	UsePublisherDNS             *bool                                `json:"use_publisher_dns,omitempty"`
}

func (p *PrivateAppsPostResponseData) GetAllowUnauthenticatedCors() *bool {
	if p == nil {
		return nil
	}
	return p.AllowUnauthenticatedCors
}

func (p *PrivateAppsPostResponseData) GetAllowURIBypass() *bool {
	if p == nil {
		return nil
	}
	return p.AllowURIBypass
}

func (p *PrivateAppsPostResponseData) GetAppID() *int {
	if p == nil {
		return nil
	}
	return p.AppID
}

func (p *PrivateAppsPostResponseData) GetPrivateAppName() *string {
	if p == nil {
		return nil
	}
	return p.PrivateAppName
}

func (p *PrivateAppsPostResponseData) GetAppOption() *PrivateAppsPostResponseAppOption {
	if p == nil {
		return nil
	}
	return p.AppOption
}

func (p *PrivateAppsPostResponseData) GetBypassUris() []string {
	if p == nil {
		return nil
	}
	return p.BypassUris
}

func (p *PrivateAppsPostResponseData) GetClientlessAccess() *bool {
	if p == nil {
		return nil
	}
	return p.ClientlessAccess
}

func (p *PrivateAppsPostResponseData) GetPrivateAppHostname() *string {
	if p == nil {
		return nil
	}
	return p.PrivateAppHostname
}

func (p *PrivateAppsPostResponseData) GetPrivateAppID() *int {
	if p == nil {
		return nil
	}
	return p.PrivateAppID
}

func (p *PrivateAppsPostResponseData) GetIsUserPortalApp() *bool {
	if p == nil {
		return nil
	}
	return p.IsUserPortalApp
}

func (p *PrivateAppsPostResponseData) GetModifiedBy() *string {
	if p == nil {
		return nil
	}
	return p.ModifiedBy
}

func (p *PrivateAppsPostResponseData) GetModifyTime() *string {
	if p == nil {
		return nil
	}
	return p.ModifyTime
}

func (p *PrivateAppsPostResponseData) GetName() *string {
	if p == nil {
		return nil
	}
	return p.Name
}

func (p *PrivateAppsPostResponseData) GetPolicies() []string {
	if p == nil {
		return nil
	}
	return p.Policies
}

func (p *PrivateAppsPostResponseData) GetPrivateAppProtocol() *string {
	if p == nil {
		return nil
	}
	return p.PrivateAppProtocol
}

func (p *PrivateAppsPostResponseData) GetProtocols() []ProtocolItem {
	if p == nil {
		return nil
	}
	return p.Protocols
}

func (p *PrivateAppsPostResponseData) GetPublicHost() *string {
	if p == nil {
		return nil
	}
	return p.PublicHost
}

func (p *PrivateAppsPostResponseData) GetReachability() *PrivateAppsPostResponseReachability {
	if p == nil {
		return nil
	}
	return p.Reachability
}

func (p *PrivateAppsPostResponseData) GetRealHost() *string {
	if p == nil {
		return nil
	}
	return p.RealHost
}

func (p *PrivateAppsPostResponseData) GetServicePublisherAssignments() []ServicePublisherAssignmentItem {
	if p == nil {
		return nil
	}
	return p.ServicePublisherAssignments
}

func (p *PrivateAppsPostResponseData) GetSteeringConfigs() []string {
	if p == nil {
		return nil
	}
	return p.SteeringConfigs
}

func (p *PrivateAppsPostResponseData) GetSupplementDNSForOsx() *bool {
	if p == nil {
		return nil
	}
	return p.SupplementDNSForOsx
}

func (p *PrivateAppsPostResponseData) GetTags() []PrivateAppsPostResponseTags {
	if p == nil {
		return nil
	}
	return p.Tags
}

func (p *PrivateAppsPostResponseData) GetTrustSelfSignedCerts() *bool {
	if p == nil {
		return nil
	}
	return p.TrustSelfSignedCerts
}

func (p *PrivateAppsPostResponseData) GetUribypassHeaderValue() *string {
	if p == nil {
		return nil
	}
	return p.UribypassHeaderValue
}

func (p *PrivateAppsPostResponseData) GetUsePublisherDNS() *bool {
	if p == nil {
		return nil
	}
	return p.UsePublisherDNS
}

type PrivateAppsPostResponse struct {
	Data   *PrivateAppsPostResponseData `json:"data,omitempty"`
	Status *string                      `json:"status,omitempty"`
}

func (p *PrivateAppsPostResponse) GetData() *PrivateAppsPostResponseData {
	if p == nil {
		return nil
	}
	return p.Data
}

func (p *PrivateAppsPostResponse) GetStatus() *string {
	if p == nil {
		return nil
	}
	return p.Status
}
