// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublisherItem struct {
	PublisherID   *string `json:"publisher_id,omitempty"`
	PublisherName *string `json:"publisher_name,omitempty"`
}

func (p *PublisherItem) GetPublisherID() *string {
	if p == nil {
		return nil
	}
	return p.PublisherID
}

func (p *PublisherItem) GetPublisherName() *string {
	if p == nil {
		return nil
	}
	return p.PublisherName
}
