// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PublisherUpgradeProfileBulkRequestApply struct {
	PublisherUpgradeProfilesID *string `json:"publisher_upgrade_profiles_id,omitempty"`
}

func (o *PublisherUpgradeProfileBulkRequestApply) GetPublisherUpgradeProfilesID() *string {
	if o == nil {
		return nil
	}
	return o.PublisherUpgradeProfilesID
}

type PublisherUpgradeProfileBulkRequestPublishers struct {
	ID    []string                                 `json:"id,omitempty"`
	Apply *PublisherUpgradeProfileBulkRequestApply `json:"apply,omitempty"`
}

func (o *PublisherUpgradeProfileBulkRequestPublishers) GetID() []string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PublisherUpgradeProfileBulkRequestPublishers) GetApply() *PublisherUpgradeProfileBulkRequestApply {
	if o == nil {
		return nil
	}
	return o.Apply
}

type PublisherUpgradeProfileBulkRequest struct {
	Publishers *PublisherUpgradeProfileBulkRequestPublishers `json:"publishers,omitempty"`
}

func (o *PublisherUpgradeProfileBulkRequest) GetPublishers() *PublisherUpgradeProfileBulkRequestPublishers {
	if o == nil {
		return nil
	}
	return o.Publishers
}
