// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PublisherPatchRequest struct {
	ID                         *int   `json:"id,omitempty"`
	Lbrokerconnect             *bool  `json:"lbrokerconnect,omitempty"`
	PublisherName              string `json:"name"`
	PublisherUpgradeProfilesID *int   `json:"publisher_upgrade_profiles_id,omitempty"`
}

func (o *PublisherPatchRequest) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PublisherPatchRequest) GetLbrokerconnect() *bool {
	if o == nil {
		return nil
	}
	return o.Lbrokerconnect
}

func (o *PublisherPatchRequest) GetPublisherName() string {
	if o == nil {
		return ""
	}
	return o.PublisherName
}

func (o *PublisherPatchRequest) GetPublisherUpgradeProfilesID() *int {
	if o == nil {
		return nil
	}
	return o.PublisherUpgradeProfilesID
}
