// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// ServiceObjectItemType - Object type — custom (user-created) or PREDEFINED (Netskope built-in, read-only) (API-computed)
type ServiceObjectItemType string

const (
	ServiceObjectItemTypeCustom     ServiceObjectItemType = "custom"
	ServiceObjectItemTypePredefined ServiceObjectItemType = "PREDEFINED"
)

func (e ServiceObjectItemType) ToPointer() *ServiceObjectItemType {
	return &e
}
func (e *ServiceObjectItemType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "custom":
		fallthrough
	case "PREDEFINED":
		*e = ServiceObjectItemType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServiceObjectItemType: %v", v)
	}
}

// ServiceObjectItemStatus - Deployment status (API-computed)
type ServiceObjectItemStatus string

const (
	ServiceObjectItemStatusApplied       ServiceObjectItemStatus = "applied"
	ServiceObjectItemStatusPendingCreate ServiceObjectItemStatus = "pending-create"
	ServiceObjectItemStatusPendingUpdate ServiceObjectItemStatus = "pending-update"
	ServiceObjectItemStatusPendingDelete ServiceObjectItemStatus = "pending-delete"
)

func (e ServiceObjectItemStatus) ToPointer() *ServiceObjectItemStatus {
	return &e
}
func (e *ServiceObjectItemStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "applied":
		fallthrough
	case "pending-create":
		fallthrough
	case "pending-update":
		fallthrough
	case "pending-delete":
		*e = ServiceObjectItemStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for ServiceObjectItemStatus: %v", v)
	}
}

type ServiceObjectItem struct {
	// Service Object UUID (assigned by API)
	ID *string `json:"id,omitempty"`
	// Service object name (unique per tenant)
	Name *string `json:"name,omitempty"`
	// Service object description
	Description *string `json:"description,omitempty"`
	// Protocol configuration. At least one protocol must be set.
	Protocols *ServiceObjectProtocols `json:"protocols,omitempty"`
	// Object type — custom (user-created) or PREDEFINED (Netskope built-in, read-only) (API-computed)
	Type *ServiceObjectItemType `json:"type,omitempty"`
	// Deployment status (API-computed)
	Status *ServiceObjectItemStatus `json:"status,omitempty"`
	// User/token that created this object (API-computed)
	CreateBy *string `json:"create_by,omitempty"`
	// Creation timestamp (API-computed)
	CreateTime *string `json:"create_time,omitempty"`
	// User/token that last modified this object (API-computed)
	ModifyBy *string `json:"modify_by,omitempty"`
	// Last modification timestamp (API-computed)
	ModifyTime *string `json:"modify_time,omitempty"`
}

func (s *ServiceObjectItem) GetID() *string {
	if s == nil {
		return nil
	}
	return s.ID
}

func (s *ServiceObjectItem) GetName() *string {
	if s == nil {
		return nil
	}
	return s.Name
}

func (s *ServiceObjectItem) GetDescription() *string {
	if s == nil {
		return nil
	}
	return s.Description
}

func (s *ServiceObjectItem) GetProtocols() *ServiceObjectProtocols {
	if s == nil {
		return nil
	}
	return s.Protocols
}

func (s *ServiceObjectItem) GetType() *ServiceObjectItemType {
	if s == nil {
		return nil
	}
	return s.Type
}

func (s *ServiceObjectItem) GetStatus() *ServiceObjectItemStatus {
	if s == nil {
		return nil
	}
	return s.Status
}

func (s *ServiceObjectItem) GetCreateBy() *string {
	if s == nil {
		return nil
	}
	return s.CreateBy
}

func (s *ServiceObjectItem) GetCreateTime() *string {
	if s == nil {
		return nil
	}
	return s.CreateTime
}

func (s *ServiceObjectItem) GetModifyBy() *string {
	if s == nil {
		return nil
	}
	return s.ModifyBy
}

func (s *ServiceObjectItem) GetModifyTime() *string {
	if s == nil {
		return nil
	}
	return s.ModifyTime
}
