// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TagPrivateAppsResponseAllDetailsAppOption struct {
}

type TagPrivateAppsResponseAllDetailsTags struct {
	ID        *int    `json:"id,omitempty"`
	Name      *string `json:"name,omitempty"`
	TagType   *string `json:"tag_type,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	UpdatedAt *string `json:"updated_at,omitempty"`
}

func (o *TagPrivateAppsResponseAllDetailsTags) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TagPrivateAppsResponseAllDetailsTags) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TagPrivateAppsResponseAllDetailsTags) GetTagType() *string {
	if o == nil {
		return nil
	}
	return o.TagType
}

func (o *TagPrivateAppsResponseAllDetailsTags) GetCreatedAt() *string {
	if o == nil {
		return nil
	}
	return o.CreatedAt
}

func (o *TagPrivateAppsResponseAllDetailsTags) GetUpdatedAt() *string {
	if o == nil {
		return nil
	}
	return o.UpdatedAt
}

type TagPrivateAppsResponseAllDetails struct {
	AllowUnauthenticatedCors    *bool                                      `json:"allow_unauthenticated_cors,omitempty"`
	AllowURIBypass              *bool                                      `json:"allow_uri_bypass,omitempty"`
	UribypassHeaderValue        *string                                    `json:"uribypass_header_value,omitempty"`
	BypassUris                  []string                                   `json:"bypass_uris,omitempty"`
	AppOption                   *TagPrivateAppsResponseAllDetailsAppOption `json:"app_option,omitempty"`
	ClientlessAccess            *bool                                      `json:"clientless_access,omitempty"`
	Host                        *string                                    `json:"host,omitempty"`
	ID                          *int                                       `json:"id,omitempty"`
	IsUserPortalApp             *bool                                      `json:"is_user_portal_app,omitempty"`
	Name                        *string                                    `json:"name,omitempty"`
	Protocols                   []ProtocolResponseItem                     `json:"protocols,omitempty"`
	RealHost                    *string                                    `json:"real_host,omitempty"`
	ServicePublisherAssignments []ServicePublisherAssignmentItem           `json:"service_publisher_assignments,omitempty"`
	Tags                        []TagPrivateAppsResponseAllDetailsTags     `json:"tags,omitempty"`
	TrustSelfSignedCerts        *bool                                      `json:"trust_self_signed_certs,omitempty"`
	UsePublisherDNS             *bool                                      `json:"use_publisher_dns,omitempty"`
}

func (o *TagPrivateAppsResponseAllDetails) GetAllowUnauthenticatedCors() *bool {
	if o == nil {
		return nil
	}
	return o.AllowUnauthenticatedCors
}

func (o *TagPrivateAppsResponseAllDetails) GetAllowURIBypass() *bool {
	if o == nil {
		return nil
	}
	return o.AllowURIBypass
}

func (o *TagPrivateAppsResponseAllDetails) GetUribypassHeaderValue() *string {
	if o == nil {
		return nil
	}
	return o.UribypassHeaderValue
}

func (o *TagPrivateAppsResponseAllDetails) GetBypassUris() []string {
	if o == nil {
		return nil
	}
	return o.BypassUris
}

func (o *TagPrivateAppsResponseAllDetails) GetAppOption() *TagPrivateAppsResponseAllDetailsAppOption {
	if o == nil {
		return nil
	}
	return o.AppOption
}

func (o *TagPrivateAppsResponseAllDetails) GetClientlessAccess() *bool {
	if o == nil {
		return nil
	}
	return o.ClientlessAccess
}

func (o *TagPrivateAppsResponseAllDetails) GetHost() *string {
	if o == nil {
		return nil
	}
	return o.Host
}

func (o *TagPrivateAppsResponseAllDetails) GetID() *int {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *TagPrivateAppsResponseAllDetails) GetIsUserPortalApp() *bool {
	if o == nil {
		return nil
	}
	return o.IsUserPortalApp
}

func (o *TagPrivateAppsResponseAllDetails) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *TagPrivateAppsResponseAllDetails) GetProtocols() []ProtocolResponseItem {
	if o == nil {
		return nil
	}
	return o.Protocols
}

func (o *TagPrivateAppsResponseAllDetails) GetRealHost() *string {
	if o == nil {
		return nil
	}
	return o.RealHost
}

func (o *TagPrivateAppsResponseAllDetails) GetServicePublisherAssignments() []ServicePublisherAssignmentItem {
	if o == nil {
		return nil
	}
	return o.ServicePublisherAssignments
}

func (o *TagPrivateAppsResponseAllDetails) GetTags() []TagPrivateAppsResponseAllDetailsTags {
	if o == nil {
		return nil
	}
	return o.Tags
}

func (o *TagPrivateAppsResponseAllDetails) GetTrustSelfSignedCerts() *bool {
	if o == nil {
		return nil
	}
	return o.TrustSelfSignedCerts
}

func (o *TagPrivateAppsResponseAllDetails) GetUsePublisherDNS() *bool {
	if o == nil {
		return nil
	}
	return o.UsePublisherDNS
}
