// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TagRequestWithIds struct {
	// these are private app ids.
	Ids  []string         `json:"ids,omitempty"`
	Tags []TagRequestItem `json:"tags,omitempty"`
}

func (o *TagRequestWithIds) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}

func (o *TagRequestWithIds) GetTags() []TagRequestItem {
	if o == nil {
		return nil
	}
	return o.Tags
}
