// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type TagResponseItem struct {
	TagID   *int    `json:"tag_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
}

func (o *TagResponseItem) GetTagID() *int {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *TagResponseItem) GetTagName() *string {
	if o == nil {
		return nil
	}
	return o.TagName
}
