// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UrllistRequest struct {
	// URL list name
	Name string             `json:"name"`
	Data UrllistRequestData `json:"data"`
}

func (u *UrllistRequest) GetName() string {
	if u == nil {
		return ""
	}
	return u.Name
}

func (u *UrllistRequest) GetData() UrllistRequestData {
	if u == nil {
		return UrllistRequestData{}
	}
	return u.Data
}
