// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type TagItem struct {
	TagID   types.Int64  `tfsdk:"tag_id"`
	TagName types.String `tfsdk:"tag_name"`
}
