workflowVersion: 1.0.0
speakeasyVersion: 1.728.0
sources:
    openapi:
        inputs:
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/base_oas.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/steering/npa_apps_private.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/steering/ipsec_tunnels.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/steering/gre_tunnels.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/policy/npa_policy.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/policy/npa_policygroup.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/infrastructure/npa_publishers.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/infrastructure/npa_upgrade_profiles.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/infrastructure/lbrokers.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/profiles/dns_profiles_v2.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/platform/ips_status.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/profiles/destination_profiles.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/profiles/custom_categories.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/profiles/service_objects.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/platform/rbac_labels.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/platform/deviceclassification_tags.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/policy/urllist.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/aig/aig-appliances-openapi.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/aig/aig-aiproviders-openapi.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/aig/aig-mcpservers-openapi.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/aig/aig-ratelimits-openapi.yaml
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/endpoints/aig/aig-tokens-openapi.yaml
        overlays:
            - location: /Users/jharris/speakeasy/netskope-apiv2-oas/terraform_overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/api-dev-ns/api-dev-ns/openapi
targets:
    first-target:
        target: terraform
        source: openapi
        publish:
            terraform:
                gpgPrivateKey: $terraform_gpg_private_key
                gpgPassPhrase: $terraform_gpg_passphrase
