workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    openapi:
        inputs:
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/base_oas.yaml
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/endpoints/steering/npa_apps_private.yaml
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/endpoints/policy/npa_policy.yaml
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/endpoints/policy/npa_policygroup.yaml
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/endpoints/infrastructure/npa_publishers.yaml
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/endpoints/infrastructure/npa_upgrade_profiles.yaml
        overlays:
            - location: /Users/jadrian/speakeasy/netskope-apiv2-oas/terraform_overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/api_dev_ns/api-dev-ns/openapi
targets:
    first-target:
        target: terraform
        source: openapi
