// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/listvalidator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	speakeasy_stringplanmodifier "github.com/netskopeoss/terraform-provider-netskope/internal/planmodifiers/stringplanmodifier"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ resource.Resource = &AIGMcpServerResource{}
var _ resource.ResourceWithImportState = &AIGMcpServerResource{}

func NewAIGMcpServerResource() resource.Resource {
	return &AIGMcpServerResource{}
}

// AIGMcpServerResource defines the resource implementation.
type AIGMcpServerResource struct {
	// Provider configured SDK client.
	client *sdk.TerraformProviderNs
}

// AIGMcpServerResourceModel describes the resource data model.
type AIGMcpServerResourceModel struct {
	Certificate types.String   `tfsdk:"certificate"`
	Host        types.String   `tfsdk:"host"`
	ID          types.String   `tfsdk:"id"`
	Name        types.String   `tfsdk:"name"`
	Path        types.String   `tfsdk:"path"`
	Port        types.Int64    `tfsdk:"port"`
	Prompts     []types.String `tfsdk:"prompts"`
	Protocol    types.String   `tfsdk:"protocol"`
	Resources   []types.String `tfsdk:"resources"`
	Schema      types.String   `tfsdk:"schema"`
	Tools       []types.String `tfsdk:"tools"`
	Type        types.String   `tfsdk:"type"`
}

func (r *AIGMcpServerResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_aig_mcp_server"
}

func (r *AIGMcpServerResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a custom MCP (Model Context Protocol) server in the Netskope AI Gateway. Custom MCP servers allow AIG appliances to proxy MCP traffic to external tool/resource endpoints for AI agent workflows.\n\nOnly custom servers (name starts with `mcp-cust-`) can be created/updated/deleted. Predefined servers are read-only.\n",
		Attributes: map[string]schema.Attribute{
			"certificate": schema.StringAttribute{
				Optional:  true,
				Sensitive: true,
				MarkdownDescription: `PEM-encoded CA certificate. Required when protocol is ` + "`" + `https-custom` + "`" + `.` + "\n" +
					`This field is write-only and not returned by the API.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(32768),
				},
			},
			"host": schema.StringAttribute{
				Required:    true,
				Description: `Hostname or FQDN of the MCP server backend.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(255),
				},
			},
			"id": schema.StringAttribute{
				Computed:    true,
				Description: `Unique identifier for the MCP server.`,
			},
			"name": schema.StringAttribute{
				Required: true,
				MarkdownDescription: `Unique name for the MCP server. Must start with ` + "`" + `mcp-cust-` + "`" + ` and contain` + "\n" +
					`only lowercase letters, numbers, and dashes (max 19 chars).`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(19),
				},
			},
			"path": schema.StringAttribute{
				Required:    true,
				Description: `URL path prefix for MCP requests.`,
				Validators: []validator.String{
					stringvalidator.UTF8LengthAtMost(255),
				},
			},
			"port": schema.Int64Attribute{
				Required:    true,
				Description: `Port number of the MCP server backend (1–65535).`,
				Validators: []validator.Int64{
					int64validator.Between(1, 65535),
				},
			},
			"prompts": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				MarkdownDescription: `List of MCP prompt names to allow through this server (max 100).` + "\n" +
					`Empty array means no filtering — all prompts are allowed.`,
				Validators: []validator.List{
					listvalidator.SizeAtMost(100),
				},
			},
			"protocol": schema.StringAttribute{
				Required: true,
				MarkdownDescription: `Connection protocol to the MCP backend:` + "\n" +
					`` + "`" + `http` + "`" + `, ` + "`" + `https-system` + "`" + `, ` + "`" + `https-custom` + "`" + `, or ` + "`" + `https-skip` + "`" + `.` + "\n" +
					`must be one of ["http", "https-system", "https-custom", "https-skip"]`,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"http",
						"https-system",
						"https-custom",
						"https-skip",
					),
				},
			},
			"resources": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				MarkdownDescription: `List of MCP resource URIs to allow through this server (max 100).` + "\n" +
					`Empty array means no filtering — all resources are allowed.`,
				Validators: []validator.List{
					listvalidator.SizeAtMost(100),
				},
			},
			"schema": schema.StringAttribute{
				Computed:    true,
				Optional:    true,
				Default:     stringdefault.StaticString(`mcp-http`),
				Description: `MCP transport schema. Currently only ` + "`" + `mcp-http` + "`" + ` is supported. Default: "mcp-http"; must be "mcp-http"`,
				Validators: []validator.String{
					stringvalidator.OneOf("mcp-http"),
				},
			},
			"tools": schema.ListAttribute{
				Computed:    true,
				Optional:    true,
				ElementType: types.StringType,
				MarkdownDescription: `List of MCP tool names to allow through this server (max 100).` + "\n" +
					`Empty array means no filtering — all tools are allowed.`,
				Validators: []validator.List{
					listvalidator.SizeAtMost(100),
				},
			},
			"type": schema.StringAttribute{
				Computed: true,
				PlanModifiers: []planmodifier.String{
					speakeasy_stringplanmodifier.SuppressDiff(speakeasy_stringplanmodifier.ExplicitSuppress),
				},
				Description: `Server type. Always "custom" for user-managed servers.`,
			},
		},
	}
}

func (r *AIGMcpServerResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.TerraformProviderNs)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *sdk.TerraformProviderNs, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *AIGMcpServerResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data *AIGMcpServerResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(plan.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToSharedAigMcpServerCreateRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.AIGMcpServer.Create(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 201 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AigMcpServer != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAigMcpServer(ctx, res.AigMcpServer)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AIGMcpServerResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data *AIGMcpServerResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetAigMcpServerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.AIGMcpServer.Read(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode == 404 {
		resp.State.RemoveResource(ctx)
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AigMcpServer != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAigMcpServer(ctx, res.AigMcpServer)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AIGMcpServerResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data *AIGMcpServerResourceModel
	var plan types.Object

	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	merge(ctx, req, resp, &data)
	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsUpdateAigMcpServerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.AIGMcpServer.Update(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.AigMcpServer != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedAigMcpServer(ctx, res.AigMcpServer)...)

	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(refreshPlan(ctx, plan, &data)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AIGMcpServerResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data *AIGMcpServerResourceModel
	var item types.Object

	resp.Diagnostics.Append(req.State.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsDeleteAigMcpServerRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.AIGMcpServer.Delete(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	switch res.StatusCode {
	case 204, 404:
		break
	default:
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}

}

func (r *AIGMcpServerResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), req.ID)...)
}
