// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *DeviceClassificationOnPremDetectionListDataSourceModel) RefreshFromSharedDeviceclassificationOnpremListResponse(ctx context.Context, resp *shared.DeviceclassificationOnpremListResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Onpremdetection = []tfTypes.DeviceclassificationOnpremItem{}

		for _, onpremdetectionItem := range resp.Onpremdetection {
			var onpremdetection tfTypes.DeviceclassificationOnpremItem

			if onpremdetectionItem.Config == nil {
				onpremdetection.Config = jsontypes.NewNormalizedNull()
			} else {
				configResult, _ := json.Marshal(onpremdetectionItem.Config)
				onpremdetection.Config = jsontypes.NewNormalizedValue(string(configResult))
			}
			onpremdetection.Name = types.StringPointerValue(onpremdetectionItem.Name)
			onpremdetection.OnpremID = types.Int64PointerValue(onpremdetectionItem.OnpremID)
			onpremdetection.SteeringIds = make([]types.Int64, 0, len(onpremdetectionItem.SteeringIds))
			for _, v := range onpremdetectionItem.SteeringIds {
				onpremdetection.SteeringIds = append(onpremdetection.SteeringIds, types.Int64Value(v))
			}

			r.Onpremdetection = append(r.Onpremdetection, onpremdetection)
		}
	}

	return diags
}

func (r *DeviceClassificationOnPremDetectionListDataSourceModel) ToOperationsListDeviceClassificationOnPremDetectionRequest(ctx context.Context) (*operations.ListDeviceClassificationOnPremDetectionRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	offset := new(int64)
	if !r.Offset.IsUnknown() && !r.Offset.IsNull() {
		*offset = r.Offset.ValueInt64()
	} else {
		offset = nil
	}
	limit := new(int64)
	if !r.Limit.IsUnknown() && !r.Limit.IsNull() {
		*limit = r.Limit.ValueInt64()
	} else {
		limit = nil
	}
	out := operations.ListDeviceClassificationOnPremDetectionRequest{
		Offset: offset,
		Limit:  limit,
	}

	return &out, diags
}
