// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-jsontypes/jsontypes"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &DeviceClassificationRuleDataSource{}
var _ datasource.DataSourceWithConfigure = &DeviceClassificationRuleDataSource{}

func NewDeviceClassificationRuleDataSource() datasource.DataSource {
	return &DeviceClassificationRuleDataSource{}
}

// DeviceClassificationRuleDataSource is the data source implementation.
type DeviceClassificationRuleDataSource struct {
	// Provider configured SDK client.
	client *sdk.TerraformProviderNs
}

// DeviceClassificationRuleDataSourceModel describes the data model.
type DeviceClassificationRuleDataSourceModel struct {
	Conditions jsontypes.Normalized `tfsdk:"conditions"`
	Label      types.String         `tfsdk:"label"`
	Name       types.String         `tfsdk:"name"`
	Os         types.String         `tfsdk:"os"`
	RuleID     types.Int64          `tfsdk:"rule_id"`
}

// Metadata returns the data source type name.
func (r *DeviceClassificationRuleDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_device_classification_rule"
}

// Schema defines the schema for the data source.
func (r *DeviceClassificationRuleDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "DeviceClassificationRule DataSource",

		Attributes: map[string]schema.Attribute{
			"conditions": schema.StringAttribute{
				CustomType:  jsontypes.NormalizedType{},
				Computed:    true,
				Description: `Nested boolean condition tree. Structure uses $and/$or operators containing check nodes (e.g. min_os_version_check, av_check, file_check, domain_check). Checks must appear at the fourth level or deeper (minimum: $and > $and > $or > check). Parsed as JSON.`,
			},
			"label": schema.StringAttribute{
				Computed:    true,
				Description: `Label (tag) name this rule belongs to`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Rule name (unique within its label)`,
			},
			"os": schema.StringAttribute{
				Computed:    true,
				Description: `Operating system this rule applies to`,
			},
			"rule_id": schema.Int64Attribute{
				Required:    true,
				Description: `Rule ID`,
			},
		},
	}
}

func (r *DeviceClassificationRuleDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.TerraformProviderNs)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.TerraformProviderNs, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *DeviceClassificationRuleDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *DeviceClassificationRuleDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetDeviceClassificationRuleRequest(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Deviceclassification.GetDeviceClassificationRule(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.DeviceclassificationRuleItem != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDeviceclassificationRuleItem(ctx, res.DeviceclassificationRuleItem)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
