// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *DeviceClassificationOptionsListDataSourceModel) RefreshFromSharedDeviceclassificationOptionsListResponse(ctx context.Context, resp *shared.DeviceclassificationOptionsListResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Options = []tfTypes.DeviceclassificationOptionItem{}

		for _, optionsVarItem := range resp.Options {
			var optionsVar tfTypes.DeviceclassificationOptionItem

			optionsVar.Key = types.StringPointerValue(optionsVarItem.Key)
			optionsVar.Os = types.StringPointerValue(optionsVarItem.Os)
			optionsVar.Type = types.StringPointerValue(optionsVarItem.Type)
			optionsVar.Value = types.StringPointerValue(optionsVarItem.Value)

			r.Options = append(r.Options, optionsVar)
		}
	}

	return diags
}

func (r *DeviceClassificationOptionsListDataSourceModel) ToOperationsListDeviceClassificationOptionsRequest(ctx context.Context) (*operations.ListDeviceClassificationOptionsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var typeVar string
	typeVar = r.Type.ValueString()

	os := new(string)
	if !r.Os.IsUnknown() && !r.Os.IsNull() {
		*os = r.Os.ValueString()
	} else {
		os = nil
	}
	out := operations.ListDeviceClassificationOptionsRequest{
		Type: typeVar,
		Os:   os,
	}

	return &out, diags
}
