// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/provider/typeconvert"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *DNSProfileV2ListDataSourceModel) RefreshFromSharedDNSProfileV2ListResponse(ctx context.Context, resp *shared.DNSProfileV2ListResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.Profiles = []tfTypes.DNSProfileV2Item{}

		for _, profilesItem := range resp.Profiles {
			var profiles tfTypes.DNSProfileV2Item

			if profilesItem.CustomConfig == nil {
				profiles.CustomConfig = nil
			} else {
				profiles.CustomConfig = &tfTypes.DNSProfileV2CustomConfig{}
				profiles.CustomConfig.BypassOriginalDNS = types.BoolPointerValue(profilesItem.CustomConfig.BypassOriginalDNS)
				profiles.CustomConfig.Enable = types.BoolPointerValue(profilesItem.CustomConfig.Enable)
				profiles.CustomConfig.FallbackToNetskopeDNS = types.BoolPointerValue(profilesItem.CustomConfig.FallbackToNetskopeDNS)
				profiles.CustomConfig.ServerIP = make([]types.String, 0, len(profilesItem.CustomConfig.ServerIP))
				for _, v := range profilesItem.CustomConfig.ServerIP {
					profiles.CustomConfig.ServerIP = append(profiles.CustomConfig.ServerIP, types.StringValue(v))
				}
			}
			profiles.Description = types.StringPointerValue(profilesItem.Description)
			if profilesItem.DomainConfig == nil {
				profiles.DomainConfig = nil
			} else {
				profiles.DomainConfig = &tfTypes.DNSProfileV2DomainConfig{}
				profiles.DomainConfig.AllowList = []tfTypes.DNSProfileV2DomainRule{}

				for _, allowListItem := range profilesItem.DomainConfig.AllowList {
					var allowList tfTypes.DNSProfileV2DomainRule

					allowList.DomainNames = make([]types.String, 0, len(allowListItem.DomainNames))
					for _, v := range allowListItem.DomainNames {
						allowList.DomainNames = append(allowList.DomainNames, types.StringValue(v))
					}
					allowList.RecordTypes = make([]types.String, 0, len(allowListItem.RecordTypes))
					for _, v := range allowListItem.RecordTypes {
						allowList.RecordTypes = append(allowList.RecordTypes, types.StringValue(v))
					}

					profiles.DomainConfig.AllowList = append(profiles.DomainConfig.AllowList, allowList)
				}
				profiles.DomainConfig.BlockAllExceptAllowList = types.BoolPointerValue(profilesItem.DomainConfig.BlockAllExceptAllowList)
				profiles.DomainConfig.BlockList = []tfTypes.DNSProfileV2DomainRule{}

				for _, blockListItem := range profilesItem.DomainConfig.BlockList {
					var blockList tfTypes.DNSProfileV2DomainRule

					blockList.DomainNames = make([]types.String, 0, len(blockListItem.DomainNames))
					for _, v := range blockListItem.DomainNames {
						blockList.DomainNames = append(blockList.DomainNames, types.StringValue(v))
					}
					blockList.RecordTypes = make([]types.String, 0, len(blockListItem.RecordTypes))
					for _, v := range blockListItem.RecordTypes {
						blockList.RecordTypes = append(blockList.RecordTypes, types.StringValue(v))
					}

					profiles.DomainConfig.BlockList = append(profiles.DomainConfig.BlockList, blockList)
				}
				profiles.DomainConfig.SecurityCategories = []tfTypes.DNSProfileV2CategoryAction{}

				for _, securityCategoriesItem := range profilesItem.DomainConfig.SecurityCategories {
					var securityCategories tfTypes.DNSProfileV2CategoryAction

					if securityCategoriesItem.Action != nil {
						securityCategories.Action = types.StringValue(string(*securityCategoriesItem.Action))
					} else {
						securityCategories.Action = types.StringNull()
					}
					securityCategories.Name = types.StringPointerValue(securityCategoriesItem.Name)

					profiles.DomainConfig.SecurityCategories = append(profiles.DomainConfig.SecurityCategories, securityCategories)
				}
				profiles.DomainConfig.SinkholeIP = types.StringPointerValue(profilesItem.DomainConfig.SinkholeIP)
			}
			profiles.InheritanceGroups = make([]types.String, 0, len(profilesItem.InheritanceGroups))
			for _, v := range profilesItem.InheritanceGroups {
				profiles.InheritanceGroups = append(profiles.InheritanceGroups, types.StringValue(v))
			}
			if profilesItem.LogTraffic != nil {
				profiles.LogTraffic = types.StringValue(string(*profilesItem.LogTraffic))
			} else {
				profiles.LogTraffic = types.StringNull()
			}
			profiles.Name = types.StringPointerValue(profilesItem.Name)
			profiles.ProfileID = types.StringPointerValue(profilesItem.ProfileID)
			if profilesItem.TunnelConfig == nil {
				profiles.TunnelConfig = nil
			} else {
				profiles.TunnelConfig = &tfTypes.DNSProfileV2TunnelConfig{}
				profiles.TunnelConfig.AllowList = make([]types.String, 0, len(profilesItem.TunnelConfig.AllowList))
				for _, v := range profilesItem.TunnelConfig.AllowList {
					profiles.TunnelConfig.AllowList = append(profiles.TunnelConfig.AllowList, types.StringValue(v))
				}
				profiles.TunnelConfig.Enable = types.BoolPointerValue(profilesItem.TunnelConfig.Enable)
			}

			r.Profiles = append(r.Profiles, profiles)
		}
		r.Total = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Total))
	}

	return diags
}

func (r *DNSProfileV2ListDataSourceModel) ToOperationsListDNSProfilesV2Request(ctx context.Context) (*operations.ListDNSProfilesV2Request, diag.Diagnostics) {
	var diags diag.Diagnostics

	out := operations.ListDNSProfilesV2Request{}

	return &out, diags
}
