// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &DNSProfileV2DataSource{}
var _ datasource.DataSourceWithConfigure = &DNSProfileV2DataSource{}

func NewDNSProfileV2DataSource() datasource.DataSource {
	return &DNSProfileV2DataSource{}
}

// DNSProfileV2DataSource is the data source implementation.
type DNSProfileV2DataSource struct {
	// Provider configured SDK client.
	client *sdk.TerraformProviderNs
}

// DNSProfileV2DataSourceModel describes the data model.
type DNSProfileV2DataSourceModel struct {
	CustomConfig      *tfTypes.DNSProfileV2CustomConfig `tfsdk:"custom_config"`
	Description       types.String                      `tfsdk:"description"`
	DomainConfig      *tfTypes.DNSProfileV2DomainConfig `tfsdk:"domain_config"`
	InheritanceGroups []types.String                    `tfsdk:"inheritance_groups"`
	LogTraffic        types.String                      `tfsdk:"log_traffic"`
	Name              types.String                      `tfsdk:"name"`
	ProfileID         types.String                      `tfsdk:"profile_id"`
	TunnelConfig      *tfTypes.DNSProfileV2TunnelConfig `tfsdk:"tunnel_config"`
}

// Metadata returns the data source type name.
func (r *DNSProfileV2DataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_dns_profile_v2"
}

// Schema defines the schema for the data source.
func (r *DNSProfileV2DataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "DNSProfileV2 DataSource",

		Attributes: map[string]schema.Attribute{
			"custom_config": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"bypass_original_dns": schema.BoolAttribute{
						Computed: true,
					},
					"enable": schema.BoolAttribute{
						Computed: true,
					},
					"fallback_to_netskope_dns": schema.BoolAttribute{
						Computed: true,
					},
					"server_ip": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
				},
			},
			"description": schema.StringAttribute{
				Computed:    true,
				Description: `Profile description`,
			},
			"domain_config": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"allow_list": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"domain_names": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"record_types": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
							},
						},
					},
					"block_all_except_allow_list": schema.BoolAttribute{
						Computed: true,
					},
					"block_list": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"domain_names": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
								"record_types": schema.ListAttribute{
									Computed:    true,
									ElementType: types.StringType,
								},
							},
						},
					},
					"security_categories": schema.ListNestedAttribute{
						Computed: true,
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"action": schema.StringAttribute{
									Computed: true,
								},
								"name": schema.StringAttribute{
									Computed: true,
								},
							},
						},
					},
					"sinkhole_ip": schema.StringAttribute{
						Computed: true,
					},
				},
			},
			"inheritance_groups": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
				Description: `Inheritance group names (max 1)`,
			},
			"log_traffic": schema.StringAttribute{
				Computed:    true,
				Description: `Traffic logging level`,
			},
			"name": schema.StringAttribute{
				Computed:    true,
				Description: `Profile name`,
			},
			"profile_id": schema.StringAttribute{
				Required:    true,
				Description: `DNS profile UUID`,
			},
			"tunnel_config": schema.SingleNestedAttribute{
				Computed: true,
				Attributes: map[string]schema.Attribute{
					"allow_list": schema.ListAttribute{
						Computed:    true,
						ElementType: types.StringType,
					},
					"enable": schema.BoolAttribute{
						Computed: true,
					},
				},
			},
		},
	}
}

func (r *DNSProfileV2DataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.TerraformProviderNs)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.TerraformProviderNs, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *DNSProfileV2DataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *DNSProfileV2DataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	request, requestDiags := data.ToOperationsGetDNSProfileV2Request(ctx)
	resp.Diagnostics.Append(requestDiags...)

	if resp.Diagnostics.HasError() {
		return
	}
	res, err := r.client.Profiles.GetDNSProfileV2(ctx, *request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.DNSProfileV2Item != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedDNSProfileV2Item(ctx, res.DNSProfileV2Item)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
