// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *GrepopDataSourceModel) RefreshFromSharedGrePopItem(ctx context.Context, resp *shared.GrePopItem) diag.Diagnostics {
	var diags diag.Diagnostics

	r.AcceptingTunnels = types.BoolPointerValue(resp.AcceptingTunnels)
	r.Bandwidth = types.StringPointerValue(resp.Bandwidth)
	r.Distance = types.StringPointerValue(resp.Distance)
	r.Gateway = types.StringPointerValue(resp.Gateway)
	r.Location = types.StringPointerValue(resp.Location)
	r.PopID = types.StringPointerValue(resp.PopID)
	r.PopName = types.StringPointerValue(resp.PopName)
	r.ProbeIP = types.StringPointerValue(resp.ProbeIP)
	r.Region = types.StringPointerValue(resp.Region)

	return diags
}

func (r *GrepopDataSourceModel) ToOperationsGetGREPOPRequest(ctx context.Context) (*operations.GetGREPOPRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var popID string
	popID = r.PopID.ValueString()

	out := operations.GetGREPOPRequest{
		PopID: popID,
	}

	return &out, diags
}
