// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/provider/typeconvert"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *GRETunnelResourceModel) RefreshFromSharedGreTunnelCreateResponse(ctx context.Context, resp *shared.GreTunnelCreateResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Data) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedGreTunnelItem(ctx, &resp.Data[0])...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *GRETunnelResourceModel) RefreshFromSharedGreTunnelGetResponse(ctx context.Context, resp *shared.GreTunnelGetResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if len(resp.Result) == 0 {
			diags.AddError("Unexpected response from API", "Missing response body array data.")
			return diags
		}

		diags.Append(r.RefreshFromSharedGreTunnelItem(ctx, &resp.Result[0])...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *GRETunnelResourceModel) RefreshFromSharedGreTunnelItem(ctx context.Context, resp *shared.GreTunnelItem) diag.Diagnostics {
	var diags diag.Diagnostics

	r.Bandwidth = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Bandwidth))
	r.Enabled = types.BoolPointerValue(resp.Enabled)
	r.Notes = types.StringPointerValue(resp.Notes)
	if resp.Options == nil {
		r.Options = nil
	} else {
		r.Options = &tfTypes.GreTunnelRequestOptions{}
		if resp.Options.Xff == nil {
			r.Options.Xff = nil
		} else {
			r.Options.Xff = &tfTypes.GreTunnelRequestXff{}
			r.Options.Xff.XffEnabled = types.BoolPointerValue(resp.Options.Xff.XffEnabled)
			r.Options.Xff.XffIPList = make([]types.String, 0, len(resp.Options.Xff.XffIPList))
			for _, v := range resp.Options.Xff.XffIPList {
				r.Options.Xff.XffIPList = append(r.Options.Xff.XffIPList, types.StringValue(v))
			}
		}
	}
	r.Site = types.StringValue(resp.Site)
	r.SourceIP = types.StringValue(resp.SourceIP)
	if resp.SourceType != nil {
		r.SourceType = types.StringValue(string(*resp.SourceType))
	} else {
		r.SourceType = types.StringNull()
	}
	r.Template = types.StringPointerValue(resp.Template)
	r.TunnelID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.TunnelID))
	r.Vendor = types.StringPointerValue(resp.Vendor)

	return diags
}

func (r *GRETunnelResourceModel) ToOperationsDeleteGRETunnelRequest(ctx context.Context) (*operations.DeleteGRETunnelRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tunnelID int
	tunnelID = int(r.TunnelID.ValueInt32())

	out := operations.DeleteGRETunnelRequest{
		TunnelID: tunnelID,
	}

	return &out, diags
}

func (r *GRETunnelResourceModel) ToOperationsGetGRETunnelRequest(ctx context.Context) (*operations.GetGRETunnelRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tunnelID int
	tunnelID = int(r.TunnelID.ValueInt32())

	out := operations.GetGRETunnelRequest{
		TunnelID: tunnelID,
	}

	return &out, diags
}

func (r *GRETunnelResourceModel) ToOperationsUpdateGRETunnelRequest(ctx context.Context) (*operations.UpdateGRETunnelRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tunnelID int
	tunnelID = int(r.TunnelID.ValueInt32())

	greTunnelRequest, greTunnelRequestDiags := r.ToSharedGreTunnelRequest(ctx)
	diags.Append(greTunnelRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateGRETunnelRequest{
		TunnelID:         tunnelID,
		GreTunnelRequest: *greTunnelRequest,
	}

	return &out, diags
}

func (r *GRETunnelResourceModel) ToSharedGreTunnelRequest(ctx context.Context) (*shared.GreTunnelRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var site string
	site = r.Site.ValueString()

	var sourceIP string
	sourceIP = r.SourceIP.ValueString()

	sourceType := new(shared.SourceType)
	if !r.SourceType.IsUnknown() && !r.SourceType.IsNull() {
		*sourceType = shared.SourceType(r.SourceType.ValueString())
	} else {
		sourceType = nil
	}
	enabled := new(bool)
	if !r.Enabled.IsUnknown() && !r.Enabled.IsNull() {
		*enabled = r.Enabled.ValueBool()
	} else {
		enabled = nil
	}
	bandwidth := new(int)
	if !r.Bandwidth.IsUnknown() && !r.Bandwidth.IsNull() {
		*bandwidth = int(r.Bandwidth.ValueInt32())
	} else {
		bandwidth = nil
	}
	template := new(string)
	if !r.Template.IsUnknown() && !r.Template.IsNull() {
		*template = r.Template.ValueString()
	} else {
		template = nil
	}
	vendor := new(string)
	if !r.Vendor.IsUnknown() && !r.Vendor.IsNull() {
		*vendor = r.Vendor.ValueString()
	} else {
		vendor = nil
	}
	notes := new(string)
	if !r.Notes.IsUnknown() && !r.Notes.IsNull() {
		*notes = r.Notes.ValueString()
	} else {
		notes = nil
	}
	popNames := make([]string, 0, len(r.PopNames))
	for popNamesIndex := range r.PopNames {
		popNames = append(popNames, r.PopNames[popNamesIndex].ValueString())
	}
	var optionsVar *shared.GreTunnelRequestOptions
	if r.Options != nil {
		var xff *shared.GreTunnelRequestXff
		if r.Options.Xff != nil {
			xffEnabled := new(bool)
			if !r.Options.Xff.XffEnabled.IsUnknown() && !r.Options.Xff.XffEnabled.IsNull() {
				*xffEnabled = r.Options.Xff.XffEnabled.ValueBool()
			} else {
				xffEnabled = nil
			}
			xffIPList := make([]string, 0, len(r.Options.Xff.XffIPList))
			for xffIPListIndex := range r.Options.Xff.XffIPList {
				xffIPList = append(xffIPList, r.Options.Xff.XffIPList[xffIPListIndex].ValueString())
			}
			xff = &shared.GreTunnelRequestXff{
				XffEnabled: xffEnabled,
				XffIPList:  xffIPList,
			}
		}
		optionsVar = &shared.GreTunnelRequestOptions{
			Xff: xff,
		}
	}
	out := shared.GreTunnelRequest{
		Site:       site,
		SourceIP:   sourceIP,
		SourceType: sourceType,
		Enabled:    enabled,
		Bandwidth:  bandwidth,
		Template:   template,
		Vendor:     vendor,
		Notes:      notes,
		PopNames:   popNames,
		Options:    optionsVar,
	}

	return &out, diags
}
