// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/provider/typeconvert"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *IPSecTunnelDataSourceModel) RefreshFromSharedIpsecTunnelItem(ctx context.Context, resp *shared.IpsecTunnelItem) diag.Diagnostics {
	var diags diag.Diagnostics

	r.Bandwidth = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.Bandwidth))
	r.Enabled = types.BoolPointerValue(resp.Enabled)
	r.Encryption = types.StringPointerValue(resp.Encryption)
	r.Notes = types.StringPointerValue(resp.Notes)
	if resp.Options == nil {
		r.Options = nil
	} else {
		r.Options = &tfTypes.IpsecTunnelRequestOptions{}
		r.Options.Reauth = types.BoolPointerValue(resp.Options.Reauth)
		r.Options.Rekey = types.BoolPointerValue(resp.Options.Rekey)
		if resp.Options.Xff == nil {
			r.Options.Xff = nil
		} else {
			r.Options.Xff = &tfTypes.IpsecTunnelRequestXff{}
			r.Options.Xff.Enabled = types.BoolPointerValue(resp.Options.Xff.Enabled)
			r.Options.Xff.Iplist = make([]types.String, 0, len(resp.Options.Xff.Iplist))
			for _, v := range resp.Options.Xff.Iplist {
				r.Options.Xff.Iplist = append(r.Options.Xff.Iplist, types.StringValue(v))
			}
		}
	}
	r.Site = types.StringPointerValue(resp.Site)
	r.SourceIdentity = types.StringPointerValue(resp.SourceIdentity)
	r.SourceIP = types.StringPointerValue(resp.SourceIP)
	r.SourceType = types.StringPointerValue(resp.SourceType)
	r.Template = types.StringPointerValue(resp.Template)
	r.TunnelID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.TunnelID))
	r.Vendor = types.StringPointerValue(resp.Vendor)

	return diags
}

func (r *IPSecTunnelDataSourceModel) ToOperationsGetIPSecTunnelRequest(ctx context.Context) (*operations.GetIPSecTunnelRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var tunnelID int
	tunnelID = int(r.TunnelID.ValueInt32())

	out := operations.GetIPSecTunnelRequest{
		TunnelID: tunnelID,
	}

	return &out, diags
}
