// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/provider/typeconvert"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *NPALocalBrokerDataSourceModel) RefreshFromSharedLbrokerItem(ctx context.Context, resp *shared.LbrokerItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		if resp.AccessViaPublicIP != nil {
			r.AccessViaPublicIP = types.StringValue(string(*resp.AccessViaPublicIP))
		} else {
			r.AccessViaPublicIP = types.StringNull()
		}
		if resp.Assessment == nil {
			r.Assessment = nil
		} else {
			r.Assessment = &tfTypes.LbrokerItemAssessment{}
			r.Assessment.Status = types.StringPointerValue(resp.Assessment.Status)
		}
		r.CityName = types.StringPointerValue(resp.CityName)
		r.CommonName = types.StringPointerValue(resp.CommonName)
		r.CountryCode = types.StringPointerValue(resp.CountryCode)
		r.CountryName = types.StringPointerValue(resp.CountryName)
		r.CreatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.CreatedAt))
		r.CustomPrivateIP = types.StringPointerValue(resp.CustomPrivateIP)
		r.CustomPublicIP = types.StringPointerValue(resp.CustomPublicIP)
		r.DiscoveredPrivateIP = types.StringPointerValue(resp.DiscoveredPrivateIP)
		r.DiscoveredPublicIP = types.StringPointerValue(resp.DiscoveredPublicIP)
		r.DNSHost = types.StringPointerValue(resp.DNSHost)
		r.GslbUUID = types.StringPointerValue(resp.GslbUUID)
		r.HostPort = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.HostPort))
		r.Latitude = types.Float32PointerValue(resp.Latitude)
		r.LocalBrokerID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.LocalBrokerID))
		r.LocalBrokerName = types.StringPointerValue(resp.LocalBrokerName)
		r.LocationID = types.StringPointerValue(resp.LocationID)
		r.Longitude = types.Float32PointerValue(resp.Longitude)
		r.PopName = types.StringPointerValue(resp.PopName)
		r.ReachableByClient = types.BoolPointerValue(resp.ReachableByClient)
		r.RegionName = types.StringPointerValue(resp.RegionName)
		r.Registered = types.BoolPointerValue(resp.Registered)
		r.RegisteredAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.RegisteredAt))
		r.UpdatedAt = types.StringPointerValue(typeconvert.TimePointerToStringPointer(resp.UpdatedAt))
	}

	return diags
}

func (r *NPALocalBrokerDataSourceModel) RefreshFromSharedLbrokerResponse(ctx context.Context, resp *shared.LbrokerResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedLbrokerItem(ctx, resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *NPALocalBrokerDataSourceModel) ToOperationsGetNPALocalBrokerByIDRequest(ctx context.Context) (*operations.GetNPALocalBrokerByIDRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var localBrokerID int
	localBrokerID = int(r.LocalBrokerID.ValueInt32())

	out := operations.GetNPALocalBrokerByIDRequest{
		LocalBrokerID: localBrokerID,
	}

	return &out, diags
}
