// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/netskope/terraform-provider-ns/internal/sdk"
	"github.com/netskope/terraform-provider-ns/internal/sdk/pkg/models/operations"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &NPAPublisherAppsDataSource{}
var _ datasource.DataSourceWithConfigure = &NPAPublisherAppsDataSource{}

func NewNPAPublisherAppsDataSource() datasource.DataSource {
	return &NPAPublisherAppsDataSource{}
}

// NPAPublisherAppsDataSource is the data source implementation.
type NPAPublisherAppsDataSource struct {
	client *sdk.SDK
}

// NPAPublisherAppsDataSourceModel describes the data model.
type NPAPublisherAppsDataSourceModel struct {
	Data        []GetInfrastructurePublishersPublisherIDAppsData `tfsdk:"data"`
	PublisherID types.Int64                                      `tfsdk:"publisher_id"`
	Status      types.String                                     `tfsdk:"status"`
}

// Metadata returns the data source type name.
func (r *NPAPublisherAppsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_npa_publisher_apps"
}

// Schema defines the schema for the data source.
func (r *NPAPublisherAppsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "NPAPublisherApps DataSource",

		Attributes: map[string]schema.Attribute{
			"data": schema.ListNestedAttribute{
				Computed: true,
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"clientless_access": schema.BoolAttribute{
							Computed: true,
						},
						"host": schema.StringAttribute{
							Computed: true,
						},
						"id": schema.Int64Attribute{
							Computed: true,
						},
						"name": schema.StringAttribute{
							Computed: true,
						},
						"protocols": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"id": schema.Int64Attribute{
										Computed: true,
									},
									"port": schema.StringAttribute{
										Computed: true,
									},
									"service_id": schema.Int64Attribute{
										Computed: true,
									},
									"transport": schema.StringAttribute{
										Computed: true,
									},
								},
							},
						},
						"real_host": schema.StringAttribute{
							Computed: true,
						},
						"service_publisher_assignments": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"primary": schema.BoolAttribute{
										Computed: true,
									},
									"publisher_id": schema.Int64Attribute{
										Computed: true,
									},
									"reachability": schema.SingleNestedAttribute{
										Computed: true,
										Attributes: map[string]schema.Attribute{
											"error_code": schema.Int64Attribute{
												Computed: true,
											},
											"error_string": schema.StringAttribute{
												Computed: true,
											},
											"reachable": schema.BoolAttribute{
												Computed: true,
											},
										},
									},
									"service_id": schema.Int64Attribute{
										Computed: true,
									},
								},
							},
						},
						"tags": schema.ListNestedAttribute{
							Computed: true,
							NestedObject: schema.NestedAttributeObject{
								Attributes: map[string]schema.Attribute{
									"tag_id": schema.Int64Attribute{
										Computed: true,
									},
									"tag_name": schema.StringAttribute{
										Computed: true,
									},
								},
							},
						},
						"trust_self_signed_certs": schema.BoolAttribute{
							Computed: true,
						},
						"use_publisher_dns": schema.BoolAttribute{
							Computed: true,
						},
					},
				},
			},
			"publisher_id": schema.Int64Attribute{
				Required:    true,
				Description: `publisher id`,
			},
			"status": schema.StringAttribute{
				Computed:    true,
				Description: `must be one of ["success", "not found"]`,
			},
		},
	}
}

func (r *NPAPublisherAppsDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.SDK)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.SDK, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *NPAPublisherAppsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *NPAPublisherAppsDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	publisherID := int(data.PublisherID.ValueInt64())
	request := operations.GetInfrastructurePublishersPublisherIDAppsRequest{
		PublisherID: publisherID,
	}
	res, err := r.client.NPAPublisherApps.ListObjects(ctx, request)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if res.TwoHundredApplicationJSONObject == nil {
		resp.Diagnostics.AddError("unexpected response from API. No response body", debugResponse(res.RawResponse))
		return
	}
	data.RefreshFromGetResponse(res.TwoHundredApplicationJSONObject)

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
