// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/provider/typeconvert"
	tfTypes "github.com/netskopeoss/terraform-provider-netskope/internal/provider/types"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/operations"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk/models/shared"
)

func (r *NPAPrivateAppResourceModel) RefreshFromSharedPrivateAppsGetResponse(ctx context.Context, resp *shared.PrivateAppsGetResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedPrivateAppsItem(ctx, resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *NPAPrivateAppResourceModel) RefreshFromSharedPrivateAppsItem(ctx context.Context, resp *shared.PrivateAppsItem) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AllowUnauthenticatedCors = types.BoolPointerValue(resp.AllowUnauthenticatedCors)
		r.AllowURIBypass = types.BoolPointerValue(resp.AllowURIBypass)
		if resp.AppOption == nil {
			r.AppOption = nil
		} else {
			r.AppOption = &tfTypes.PrivateAppsRequestAppOption{}
		}
		if resp.BypassUris != nil {
			r.BypassUris = make([]types.String, 0, len(resp.BypassUris))
			for _, v := range resp.BypassUris {
				r.BypassUris = append(r.BypassUris, types.StringValue(v))
			}
		} else {
			r.BypassUris = nil
		}
		r.ClientlessAccess = types.BoolPointerValue(resp.ClientlessAccess)
		r.CustomHost = types.StringPointerValue(resp.CustomHost)
		r.HideAppInPortal = types.BoolPointerValue(resp.HideAppInPortal)
		r.IsUserPortalApp = types.BoolPointerValue(resp.IsUserPortalApp)
		r.LabelIds = make([]types.String, 0, len(resp.LabelIds))
		for _, v := range resp.LabelIds {
			r.LabelIds = append(r.LabelIds, types.StringValue(v))
		}
		if resp.Paths != nil {
			r.Paths = make([]types.String, 0, len(resp.Paths))
			for _, v := range resp.Paths {
				r.Paths = append(r.Paths, types.StringValue(v))
			}
		} else {
			r.Paths = nil
		}
		r.PrivateAppHostname = types.StringPointerValue(resp.PrivateAppHostname)
		r.PrivateAppID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PrivateAppID))
		r.PrivateAppName = types.StringPointerValue(resp.PrivateAppName)
		r.PrivateAppProtocol = types.StringPointerValue(resp.PrivateAppProtocol)
		r.Protocols = []tfTypes.ProtocolItem{}

		for _, protocolsItem := range resp.Protocols {
			var protocols tfTypes.ProtocolItem

			protocols.Port = types.StringPointerValue(protocolsItem.Port)
			if protocolsItem.Protocol != nil {
				protocols.Protocol = types.StringValue(string(*protocolsItem.Protocol))
			} else {
				protocols.Protocol = types.StringNull()
			}

			r.Protocols = append(r.Protocols, protocols)
		}
		r.Publishers = []tfTypes.PublisherItem{}

		for _, publishersItem := range resp.Publishers {
			var publishers tfTypes.PublisherItem

			publishers.PublisherID = types.StringPointerValue(publishersItem.PublisherID)
			publishers.PublisherName = types.StringPointerValue(publishersItem.PublisherName)

			r.Publishers = append(r.Publishers, publishers)
		}
		r.RealHost = types.StringPointerValue(resp.RealHost)
		r.Tags = []tfTypes.Tags{}

		for _, tagsItem := range resp.Tags {
			var tags tfTypes.Tags

			tags.TagID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(tagsItem.TagID))
			tags.TagName = types.StringPointerValue(tagsItem.TagName)

			r.Tags = append(r.Tags, tags)
		}
		r.TrustSelfSignedCerts = types.BoolPointerValue(resp.TrustSelfSignedCerts)
		r.UpgradeInsecureRequests = types.BoolPointerValue(resp.UpgradeInsecureRequests)
		r.UribypassHeaderValue = types.StringPointerValue(resp.UribypassHeaderValue)
		r.UsePublisherDNS = types.BoolPointerValue(resp.UsePublisherDNS)
	}

	return diags
}

func (r *NPAPrivateAppResourceModel) RefreshFromSharedPrivateAppsPostResponse(ctx context.Context, resp *shared.PrivateAppsPostResponse) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		diags.Append(r.RefreshFromSharedPrivateAppsPostResponseData(ctx, resp.Data)...)

		if diags.HasError() {
			return diags
		}

	}

	return diags
}

func (r *NPAPrivateAppResourceModel) RefreshFromSharedPrivateAppsPostResponseData(ctx context.Context, resp *shared.PrivateAppsPostResponseData) diag.Diagnostics {
	var diags diag.Diagnostics

	if resp != nil {
		r.AllowUnauthenticatedCors = types.BoolPointerValue(resp.AllowUnauthenticatedCors)
		r.AllowURIBypass = types.BoolPointerValue(resp.AllowURIBypass)
		if resp.AppOption == nil {
			r.AppOption = nil
		} else {
			r.AppOption = &tfTypes.PrivateAppsRequestAppOption{}
		}
		if resp.BypassUris != nil {
			r.BypassUris = make([]types.String, 0, len(resp.BypassUris))
			for _, v := range resp.BypassUris {
				r.BypassUris = append(r.BypassUris, types.StringValue(v))
			}
		} else {
			r.BypassUris = nil
		}
		r.ClientlessAccess = types.BoolPointerValue(resp.ClientlessAccess)
		r.CustomHost = types.StringPointerValue(resp.CustomHost)
		r.HideAppInPortal = types.BoolPointerValue(resp.HideAppInPortal)
		r.IsUserPortalApp = types.BoolPointerValue(resp.IsUserPortalApp)
		if resp.Paths != nil {
			r.Paths = make([]types.String, 0, len(resp.Paths))
			for _, v := range resp.Paths {
				r.Paths = append(r.Paths, types.StringValue(v))
			}
		} else {
			r.Paths = nil
		}
		r.PrivateAppHostname = types.StringPointerValue(resp.PrivateAppHostname)
		r.PrivateAppID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(resp.PrivateAppID))
		r.PrivateAppName = types.StringPointerValue(resp.PrivateAppName)
		r.PrivateAppProtocol = types.StringPointerValue(resp.PrivateAppProtocol)
		r.Protocols = []tfTypes.ProtocolItem{}

		for _, protocolsItem := range resp.Protocols {
			var protocols tfTypes.ProtocolItem

			protocols.Port = types.StringPointerValue(protocolsItem.Port)
			if protocolsItem.Protocol != nil {
				protocols.Protocol = types.StringValue(string(*protocolsItem.Protocol))
			} else {
				protocols.Protocol = types.StringNull()
			}

			r.Protocols = append(r.Protocols, protocols)
		}
		r.RealHost = types.StringPointerValue(resp.RealHost)
		r.Tags = []tfTypes.Tags{}

		for _, tagsItem := range resp.Tags {
			var tags tfTypes.Tags

			tags.TagID = types.Int32PointerValue(typeconvert.IntPointerToInt32Pointer(tagsItem.TagID))
			tags.TagName = types.StringPointerValue(tagsItem.TagName)

			r.Tags = append(r.Tags, tags)
		}
		r.TrustSelfSignedCerts = types.BoolPointerValue(resp.TrustSelfSignedCerts)
		r.UpgradeInsecureRequests = types.BoolPointerValue(resp.UpgradeInsecureRequests)
		r.UribypassHeaderValue = types.StringPointerValue(resp.UribypassHeaderValue)
		r.UsePublisherDNS = types.BoolPointerValue(resp.UsePublisherDNS)
	}

	return diags
}

func (r *NPAPrivateAppResourceModel) ToOperationsDeleteNPAPrivateAppRequest(ctx context.Context) (*operations.DeleteNPAPrivateAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var privateAppID int
	privateAppID = int(r.PrivateAppID.ValueInt32())

	out := operations.DeleteNPAPrivateAppRequest{
		PrivateAppID: privateAppID,
	}

	return &out, diags
}

func (r *NPAPrivateAppResourceModel) ToOperationsGetNPAPrivateAppRequest(ctx context.Context) (*operations.GetNPAPrivateAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var privateAppID int
	privateAppID = int(r.PrivateAppID.ValueInt32())

	out := operations.GetNPAPrivateAppRequest{
		PrivateAppID: privateAppID,
	}

	return &out, diags
}

func (r *NPAPrivateAppResourceModel) ToOperationsUpdateNPAPrivateAppRequest(ctx context.Context) (*operations.UpdateNPAPrivateAppRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	var privateAppID int
	privateAppID = int(r.PrivateAppID.ValueInt32())

	privateAppsPutRequest, privateAppsPutRequestDiags := r.ToSharedPrivateAppsPutRequest(ctx)
	diags.Append(privateAppsPutRequestDiags...)

	if diags.HasError() {
		return nil, diags
	}

	out := operations.UpdateNPAPrivateAppRequest{
		PrivateAppID:          privateAppID,
		PrivateAppsPutRequest: *privateAppsPutRequest,
	}

	return &out, diags
}

func (r *NPAPrivateAppResourceModel) ToSharedPrivateAppsPutRequest(ctx context.Context) (*shared.PrivateAppsPutRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	allowUnauthenticatedCors := new(bool)
	if !r.AllowUnauthenticatedCors.IsUnknown() && !r.AllowUnauthenticatedCors.IsNull() {
		*allowUnauthenticatedCors = r.AllowUnauthenticatedCors.ValueBool()
	} else {
		allowUnauthenticatedCors = nil
	}
	allowURIBypass := new(bool)
	if !r.AllowURIBypass.IsUnknown() && !r.AllowURIBypass.IsNull() {
		*allowURIBypass = r.AllowURIBypass.ValueBool()
	} else {
		allowURIBypass = nil
	}
	uribypassHeaderValue := new(string)
	if !r.UribypassHeaderValue.IsUnknown() && !r.UribypassHeaderValue.IsNull() {
		*uribypassHeaderValue = r.UribypassHeaderValue.ValueString()
	} else {
		uribypassHeaderValue = nil
	}
	bypassUris := make([]string, 0, len(r.BypassUris))
	for bypassUrisIndex := range r.BypassUris {
		bypassUris = append(bypassUris, r.BypassUris[bypassUrisIndex].ValueString())
	}
	var appOption *shared.PrivateAppsPutRequestAppOption
	if r.AppOption != nil {
		appOption = &shared.PrivateAppsPutRequestAppOption{}
	}
	clientlessAccess := new(bool)
	if !r.ClientlessAccess.IsUnknown() && !r.ClientlessAccess.IsNull() {
		*clientlessAccess = r.ClientlessAccess.ValueBool()
	} else {
		clientlessAccess = nil
	}
	hideAppInPortal := new(bool)
	if !r.HideAppInPortal.IsUnknown() && !r.HideAppInPortal.IsNull() {
		*hideAppInPortal = r.HideAppInPortal.ValueBool()
	} else {
		hideAppInPortal = nil
	}
	privateAppHostname := new(string)
	if !r.PrivateAppHostname.IsUnknown() && !r.PrivateAppHostname.IsNull() {
		*privateAppHostname = r.PrivateAppHostname.ValueString()
	} else {
		privateAppHostname = nil
	}
	privateAppID := new(int)
	if !r.PrivateAppID.IsUnknown() && !r.PrivateAppID.IsNull() {
		*privateAppID = int(r.PrivateAppID.ValueInt32())
	} else {
		privateAppID = nil
	}
	isUserPortalApp := new(bool)
	if !r.IsUserPortalApp.IsUnknown() && !r.IsUserPortalApp.IsNull() {
		*isUserPortalApp = r.IsUserPortalApp.ValueBool()
	} else {
		isUserPortalApp = nil
	}
	labelIds := make([]string, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueString())
	}
	protocols := make([]shared.ProtocolItem, 0, len(r.Protocols))
	for protocolsIndex := range r.Protocols {
		port := new(string)
		if !r.Protocols[protocolsIndex].Port.IsUnknown() && !r.Protocols[protocolsIndex].Port.IsNull() {
			*port = r.Protocols[protocolsIndex].Port.ValueString()
		} else {
			port = nil
		}
		protocol := new(shared.Protocol)
		if !r.Protocols[protocolsIndex].Protocol.IsUnknown() && !r.Protocols[protocolsIndex].Protocol.IsNull() {
			*protocol = shared.Protocol(r.Protocols[protocolsIndex].Protocol.ValueString())
		} else {
			protocol = nil
		}
		protocols = append(protocols, shared.ProtocolItem{
			Port:     port,
			Protocol: protocol,
		})
	}
	paths := make([]string, 0, len(r.Paths))
	for pathsIndex := range r.Paths {
		paths = append(paths, r.Paths[pathsIndex].ValueString())
	}
	publishers := make([]shared.PublisherItem, 0, len(r.Publishers))
	for publishersIndex := range r.Publishers {
		publisherID := new(string)
		if !r.Publishers[publishersIndex].PublisherID.IsUnknown() && !r.Publishers[publishersIndex].PublisherID.IsNull() {
			*publisherID = r.Publishers[publishersIndex].PublisherID.ValueString()
		} else {
			publisherID = nil
		}
		publisherName := new(string)
		if !r.Publishers[publishersIndex].PublisherName.IsUnknown() && !r.Publishers[publishersIndex].PublisherName.IsNull() {
			*publisherName = r.Publishers[publishersIndex].PublisherName.ValueString()
		} else {
			publisherName = nil
		}
		publishers = append(publishers, shared.PublisherItem{
			PublisherID:   publisherID,
			PublisherName: publisherName,
		})
	}
	realHost := new(string)
	if !r.RealHost.IsUnknown() && !r.RealHost.IsNull() {
		*realHost = r.RealHost.ValueString()
	} else {
		realHost = nil
	}
	tags := make([]shared.PrivateAppsPutRequestTags, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tagName := new(string)
		if !r.Tags[tagsIndex].TagName.IsUnknown() && !r.Tags[tagsIndex].TagName.IsNull() {
			*tagName = r.Tags[tagsIndex].TagName.ValueString()
		} else {
			tagName = nil
		}
		tags = append(tags, shared.PrivateAppsPutRequestTags{
			TagName: tagName,
		})
	}
	trustSelfSignedCerts := new(bool)
	if !r.TrustSelfSignedCerts.IsUnknown() && !r.TrustSelfSignedCerts.IsNull() {
		*trustSelfSignedCerts = r.TrustSelfSignedCerts.ValueBool()
	} else {
		trustSelfSignedCerts = nil
	}
	upgradeInsecureRequests := new(bool)
	if !r.UpgradeInsecureRequests.IsUnknown() && !r.UpgradeInsecureRequests.IsNull() {
		*upgradeInsecureRequests = r.UpgradeInsecureRequests.ValueBool()
	} else {
		upgradeInsecureRequests = nil
	}
	usePublisherDNS := new(bool)
	if !r.UsePublisherDNS.IsUnknown() && !r.UsePublisherDNS.IsNull() {
		*usePublisherDNS = r.UsePublisherDNS.ValueBool()
	} else {
		usePublisherDNS = nil
	}
	out := shared.PrivateAppsPutRequest{
		AllowUnauthenticatedCors: allowUnauthenticatedCors,
		AllowURIBypass:           allowURIBypass,
		UribypassHeaderValue:     uribypassHeaderValue,
		BypassUris:               bypassUris,
		AppOption:                appOption,
		ClientlessAccess:         clientlessAccess,
		HideAppInPortal:          hideAppInPortal,
		PrivateAppHostname:       privateAppHostname,
		PrivateAppID:             privateAppID,
		IsUserPortalApp:          isUserPortalApp,
		LabelIds:                 labelIds,
		Protocols:                protocols,
		Paths:                    paths,
		Publishers:               publishers,
		RealHost:                 realHost,
		Tags:                     tags,
		TrustSelfSignedCerts:     trustSelfSignedCerts,
		UpgradeInsecureRequests:  upgradeInsecureRequests,
		UsePublisherDNS:          usePublisherDNS,
	}

	return &out, diags
}

func (r *NPAPrivateAppResourceModel) ToSharedPrivateAppsRequest(ctx context.Context) (*shared.PrivateAppsRequest, diag.Diagnostics) {
	var diags diag.Diagnostics

	allowUnauthenticatedCors := new(bool)
	if !r.AllowUnauthenticatedCors.IsUnknown() && !r.AllowUnauthenticatedCors.IsNull() {
		*allowUnauthenticatedCors = r.AllowUnauthenticatedCors.ValueBool()
	} else {
		allowUnauthenticatedCors = nil
	}
	allowURIBypass := new(bool)
	if !r.AllowURIBypass.IsUnknown() && !r.AllowURIBypass.IsNull() {
		*allowURIBypass = r.AllowURIBypass.ValueBool()
	} else {
		allowURIBypass = nil
	}
	uribypassHeaderValue := new(string)
	if !r.UribypassHeaderValue.IsUnknown() && !r.UribypassHeaderValue.IsNull() {
		*uribypassHeaderValue = r.UribypassHeaderValue.ValueString()
	} else {
		uribypassHeaderValue = nil
	}
	var bypassUris []string
	if r.BypassUris != nil {
		bypassUris = make([]string, 0, len(r.BypassUris))
		for bypassUrisIndex := range r.BypassUris {
			bypassUris = append(bypassUris, r.BypassUris[bypassUrisIndex].ValueString())
		}
	}
	privateAppName := new(string)
	if !r.PrivateAppName.IsUnknown() && !r.PrivateAppName.IsNull() {
		*privateAppName = r.PrivateAppName.ValueString()
	} else {
		privateAppName = nil
	}
	var appOption *shared.PrivateAppsRequestAppOption
	if r.AppOption != nil {
		appOption = &shared.PrivateAppsRequestAppOption{}
	}
	clientlessAccess := new(bool)
	if !r.ClientlessAccess.IsUnknown() && !r.ClientlessAccess.IsNull() {
		*clientlessAccess = r.ClientlessAccess.ValueBool()
	} else {
		clientlessAccess = nil
	}
	hideAppInPortal := new(bool)
	if !r.HideAppInPortal.IsUnknown() && !r.HideAppInPortal.IsNull() {
		*hideAppInPortal = r.HideAppInPortal.ValueBool()
	} else {
		hideAppInPortal = nil
	}
	privateAppHostname := new(string)
	if !r.PrivateAppHostname.IsUnknown() && !r.PrivateAppHostname.IsNull() {
		*privateAppHostname = r.PrivateAppHostname.ValueString()
	} else {
		privateAppHostname = nil
	}
	isUserPortalApp := new(bool)
	if !r.IsUserPortalApp.IsUnknown() && !r.IsUserPortalApp.IsNull() {
		*isUserPortalApp = r.IsUserPortalApp.ValueBool()
	} else {
		isUserPortalApp = nil
	}
	labelIds := make([]string, 0, len(r.LabelIds))
	for labelIdsIndex := range r.LabelIds {
		labelIds = append(labelIds, r.LabelIds[labelIdsIndex].ValueString())
	}
	protocols := make([]shared.ProtocolItem, 0, len(r.Protocols))
	for protocolsIndex := range r.Protocols {
		port := new(string)
		if !r.Protocols[protocolsIndex].Port.IsUnknown() && !r.Protocols[protocolsIndex].Port.IsNull() {
			*port = r.Protocols[protocolsIndex].Port.ValueString()
		} else {
			port = nil
		}
		protocol := new(shared.Protocol)
		if !r.Protocols[protocolsIndex].Protocol.IsUnknown() && !r.Protocols[protocolsIndex].Protocol.IsNull() {
			*protocol = shared.Protocol(r.Protocols[protocolsIndex].Protocol.ValueString())
		} else {
			protocol = nil
		}
		protocols = append(protocols, shared.ProtocolItem{
			Port:     port,
			Protocol: protocol,
		})
	}
	var paths []string
	if r.Paths != nil {
		paths = make([]string, 0, len(r.Paths))
		for pathsIndex := range r.Paths {
			paths = append(paths, r.Paths[pathsIndex].ValueString())
		}
	}
	publishers := make([]shared.PublisherItem, 0, len(r.Publishers))
	for publishersIndex := range r.Publishers {
		publisherID := new(string)
		if !r.Publishers[publishersIndex].PublisherID.IsUnknown() && !r.Publishers[publishersIndex].PublisherID.IsNull() {
			*publisherID = r.Publishers[publishersIndex].PublisherID.ValueString()
		} else {
			publisherID = nil
		}
		publisherName := new(string)
		if !r.Publishers[publishersIndex].PublisherName.IsUnknown() && !r.Publishers[publishersIndex].PublisherName.IsNull() {
			*publisherName = r.Publishers[publishersIndex].PublisherName.ValueString()
		} else {
			publisherName = nil
		}
		publishers = append(publishers, shared.PublisherItem{
			PublisherID:   publisherID,
			PublisherName: publisherName,
		})
	}
	tags := make([]shared.PrivateAppsRequestTags, 0, len(r.Tags))
	for tagsIndex := range r.Tags {
		tagName := new(string)
		if !r.Tags[tagsIndex].TagName.IsUnknown() && !r.Tags[tagsIndex].TagName.IsNull() {
			*tagName = r.Tags[tagsIndex].TagName.ValueString()
		} else {
			tagName = nil
		}
		tags = append(tags, shared.PrivateAppsRequestTags{
			TagName: tagName,
		})
	}
	realHost := new(string)
	if !r.RealHost.IsUnknown() && !r.RealHost.IsNull() {
		*realHost = r.RealHost.ValueString()
	} else {
		realHost = nil
	}
	privateAppProtocol := new(string)
	if !r.PrivateAppProtocol.IsUnknown() && !r.PrivateAppProtocol.IsNull() {
		*privateAppProtocol = r.PrivateAppProtocol.ValueString()
	} else {
		privateAppProtocol = nil
	}
	trustSelfSignedCerts := new(bool)
	if !r.TrustSelfSignedCerts.IsUnknown() && !r.TrustSelfSignedCerts.IsNull() {
		*trustSelfSignedCerts = r.TrustSelfSignedCerts.ValueBool()
	} else {
		trustSelfSignedCerts = nil
	}
	upgradeInsecureRequests := new(bool)
	if !r.UpgradeInsecureRequests.IsUnknown() && !r.UpgradeInsecureRequests.IsNull() {
		*upgradeInsecureRequests = r.UpgradeInsecureRequests.ValueBool()
	} else {
		upgradeInsecureRequests = nil
	}
	usePublisherDNS := new(bool)
	if !r.UsePublisherDNS.IsUnknown() && !r.UsePublisherDNS.IsNull() {
		*usePublisherDNS = r.UsePublisherDNS.ValueBool()
	} else {
		usePublisherDNS = nil
	}
	out := shared.PrivateAppsRequest{
		AllowUnauthenticatedCors: allowUnauthenticatedCors,
		AllowURIBypass:           allowURIBypass,
		UribypassHeaderValue:     uribypassHeaderValue,
		BypassUris:               bypassUris,
		PrivateAppName:           privateAppName,
		AppOption:                appOption,
		ClientlessAccess:         clientlessAccess,
		HideAppInPortal:          hideAppInPortal,
		PrivateAppHostname:       privateAppHostname,
		IsUserPortalApp:          isUserPortalApp,
		LabelIds:                 labelIds,
		Protocols:                protocols,
		Paths:                    paths,
		Publishers:               publishers,
		Tags:                     tags,
		RealHost:                 realHost,
		PrivateAppProtocol:       privateAppProtocol,
		TrustSelfSignedCerts:     trustSelfSignedCerts,
		UpgradeInsecureRequests:  upgradeInsecureRequests,
		UsePublisherDNS:          usePublisherDNS,
	}

	return &out, diags
}
