// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/speakeasy/terraform-provider-terraform/internal/sdk/models/shared"
)

func (r *NPAPublishersAlertsConfigurationListDataSourceModel) RefreshFromSharedPublishersAlertGetResponseData(resp *shared.PublishersAlertGetResponseData) {
	if resp != nil {
		r.AdminUsers = []types.String{}
		for _, v := range resp.AdminUsers {
			r.AdminUsers = append(r.AdminUsers, types.StringValue(v))
		}
		r.EventTypes = []types.String{}
		for _, v := range resp.EventTypes {
			r.EventTypes = append(r.EventTypes, types.StringValue(string(v)))
		}
		r.SelectedUsers = types.StringPointerValue(resp.SelectedUsers)
	}
}
