// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"ns/internal/sdk/pkg/models/operations"
)

func (r *NPAPolicyGroupResourceModel) ToCreateSDKType() *operations.PostPolicyNpaPolicygroupsRequestBody {
	groupName := new(string)
	if !r.GroupName.IsUnknown() && !r.GroupName.IsNull() {
		*groupName = r.GroupName.ValueString()
	} else {
		groupName = nil
	}
	var groupOrder *operations.PostPolicyNpaPolicygroupsGroupOrder
	if r.GroupOrder != nil {
		var groupOrder1 *operations.PostPolicyNpaPolicygroupsRequestGroupOrder
		if r.GroupOrder.GroupOrder != nil {
			groupID := new(string)
			if !r.GroupOrder.GroupOrder.GroupID.IsUnknown() && !r.GroupOrder.GroupOrder.GroupID.IsNull() {
				*groupID = r.GroupOrder.GroupOrder.GroupID.ValueString()
			} else {
				groupID = nil
			}
			order := new(operations.PostPolicyNpaPolicygroupsOrder)
			if !r.GroupOrder.GroupOrder.Order.IsUnknown() && !r.GroupOrder.GroupOrder.Order.IsNull() {
				*order = operations.PostPolicyNpaPolicygroupsOrder(r.GroupOrder.GroupOrder.Order.ValueString())
			} else {
				order = nil
			}
			groupOrder1 = &operations.PostPolicyNpaPolicygroupsRequestGroupOrder{
				GroupID: groupID,
				Order:   order,
			}
		}
		groupOrder = &operations.PostPolicyNpaPolicygroupsGroupOrder{
			GroupOrder: groupOrder1,
		}
	}
	modifyBy := new(string)
	if !r.ModifyBy.IsUnknown() && !r.ModifyBy.IsNull() {
		*modifyBy = r.ModifyBy.ValueString()
	} else {
		modifyBy = nil
	}
	modifyType := new(string)
	if !r.ModifyType.IsUnknown() && !r.ModifyType.IsNull() {
		*modifyType = r.ModifyType.ValueString()
	} else {
		modifyType = nil
	}
	out := operations.PostPolicyNpaPolicygroupsRequestBody{
		GroupName:  groupName,
		GroupOrder: groupOrder,
		ModifyBy:   modifyBy,
		ModifyType: modifyType,
	}
	return &out
}

func (r *NPAPolicyGroupResourceModel) ToGetSDKType() *operations.PostPolicyNpaPolicygroupsRequestBody {
	out := r.ToCreateSDKType()
	return out
}

func (r *NPAPolicyGroupResourceModel) ToDeleteSDKType() *operations.PostPolicyNpaPolicygroupsRequestBody {
	out := r.ToCreateSDKType()
	return out
}

func (r *NPAPolicyGroupResourceModel) RefreshFromGetResponse(resp *operations.GetPolicyNpaPolicygroupsIDResponseBody) {
	if resp.CanBeEditedDeleted != nil {
		r.CanBeEditedDeleted = types.Int64Value(*resp.CanBeEditedDeleted)
	} else {
		r.CanBeEditedDeleted = types.Int64Null()
	}
	if resp.GroupID != nil {
		r.GroupID = types.Int64Value(*resp.GroupID)
	} else {
		r.GroupID = types.Int64Null()
	}
	if resp.GroupName != nil {
		r.GroupName = types.StringValue(*resp.GroupName)
	} else {
		r.GroupName = types.StringNull()
	}
	if resp.GroupPinnedID != nil {
		r.GroupPinnedID = types.Int64Value(*resp.GroupPinnedID)
	} else {
		r.GroupPinnedID = types.Int64Null()
	}
	if resp.GroupProdID != nil {
		r.GroupProdID = types.Int64Value(*resp.GroupProdID)
	} else {
		r.GroupProdID = types.Int64Null()
	}
	if resp.GroupType != nil {
		r.GroupType = types.Int64Value(*resp.GroupType)
	} else {
		r.GroupType = types.Int64Null()
	}
	if resp.ModifyTime != nil {
		r.ModifyTime = types.StringValue(*resp.ModifyTime)
	} else {
		r.ModifyTime = types.StringNull()
	}
	if resp.ModifyType != nil {
		r.ModifyType = types.StringValue(*resp.ModifyType)
	} else {
		r.ModifyType = types.StringNull()
	}
}

func (r *NPAPolicyGroupResourceModel) RefreshFromCreateResponse(resp *operations.PostPolicyNpaPolicygroupsResponseBody) {
	if resp.CanBeEditedDeleted != nil {
		r.CanBeEditedDeleted = types.Int64Value(*resp.CanBeEditedDeleted)
	} else {
		r.CanBeEditedDeleted = types.Int64Null()
	}
	if resp.GroupID != nil {
		r.GroupID = types.Int64Value(*resp.GroupID)
	} else {
		r.GroupID = types.Int64Null()
	}
	if resp.GroupName != nil {
		r.GroupName = types.StringValue(*resp.GroupName)
	} else {
		r.GroupName = types.StringNull()
	}
	if resp.GroupPinnedID != nil {
		r.GroupPinnedID = types.Int64Value(*resp.GroupPinnedID)
	} else {
		r.GroupPinnedID = types.Int64Null()
	}
	if resp.GroupProdID != nil {
		r.GroupProdID = types.Int64Value(*resp.GroupProdID)
	} else {
		r.GroupProdID = types.Int64Null()
	}
	if resp.GroupType != nil {
		r.GroupType = types.Int64Value(*resp.GroupType)
	} else {
		r.GroupType = types.Int64Null()
	}
	if resp.ModifyTime != nil {
		r.ModifyTime = types.StringValue(*resp.ModifyTime)
	} else {
		r.ModifyTime = types.StringNull()
	}
	if resp.ModifyType != nil {
		r.ModifyType = types.StringValue(*resp.ModifyType)
	} else {
		r.ModifyType = types.StringNull()
	}
}
