// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskope/terraform-provider-ns/internal/sdk/pkg/models/shared"
)

func (r *NPAPublishersAlertsConfigurationResourceModel) ToCreateSDKType() *shared.PublishersAlertPutRequest {
	var adminUsers []string = nil
	for _, adminUsersItem := range r.AdminUsers {
		adminUsers = append(adminUsers, adminUsersItem.ValueString())
	}
	var eventTypes []shared.EventTypes = nil
	for _, eventTypesItem := range r.EventTypes {
		eventTypes = append(eventTypes, shared.EventTypes(eventTypesItem.ValueString()))
	}
	selectedUsers := new(string)
	if !r.SelectedUsers.IsUnknown() && !r.SelectedUsers.IsNull() {
		*selectedUsers = r.SelectedUsers.ValueString()
	} else {
		selectedUsers = nil
	}
	out := shared.PublishersAlertPutRequest{
		AdminUsers:    adminUsers,
		EventTypes:    eventTypes,
		SelectedUsers: selectedUsers,
	}
	return &out
}

func (r *NPAPublishersAlertsConfigurationResourceModel) ToUpdateSDKType() *shared.PublishersAlertPutRequest {
	out := r.ToCreateSDKType()
	return out
}

func (r *NPAPublishersAlertsConfigurationResourceModel) RefreshFromGetResponse(resp *shared.PublishersAlertGetResponseData) {
	r.AdminUsers = nil
	for _, v := range resp.AdminUsers {
		r.AdminUsers = append(r.AdminUsers, types.StringValue(v))
	}
	r.EventTypes = nil
	for _, v := range resp.EventTypes {
		r.EventTypes = append(r.EventTypes, types.StringValue(string(v)))
	}
	if resp.SelectedUsers != nil {
		r.SelectedUsers = types.StringValue(*resp.SelectedUsers)
	} else {
		r.SelectedUsers = types.StringNull()
	}
}

func (r *NPAPublishersAlertsConfigurationResourceModel) RefreshFromCreateResponse(resp *shared.PublishersAlertGetResponseData) {
	r.RefreshFromGetResponse(resp)
}

func (r *NPAPublishersAlertsConfigurationResourceModel) RefreshFromUpdateResponse(resp *shared.PublishersAlertGetResponseData) {
	r.RefreshFromGetResponse(resp)
}
