// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/netskope/terraform-provider-ns/internal/sdk/models/shared"
)

func (r *NPAPolicyGroupDataSourceModel) RefreshFromSharedNpaPolicygroupResponseItem(resp *shared.NpaPolicygroupResponseItem) {
	if resp != nil {
		r.CanBeEditedDeleted = types.StringPointerValue(resp.CanBeEditedDeleted)
		r.GroupName = types.StringPointerValue(resp.GroupName)
		r.ID = types.StringPointerValue(resp.ID)
	}
}
