// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package provider

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/netskopeoss/terraform-provider-netskope/internal/sdk"
)

// Ensure provider defined types fully satisfy framework interfaces.
var _ datasource.DataSource = &NPAPublishersAlertsConfigurationDataSource{}
var _ datasource.DataSourceWithConfigure = &NPAPublishersAlertsConfigurationDataSource{}

func NewNPAPublishersAlertsConfigurationDataSource() datasource.DataSource {
	return &NPAPublishersAlertsConfigurationDataSource{}
}

// NPAPublishersAlertsConfigurationDataSource is the data source implementation.
type NPAPublishersAlertsConfigurationDataSource struct {
	// Provider configured SDK client.
	client *sdk.TerraformProviderNs
}

// NPAPublishersAlertsConfigurationDataSourceModel describes the data model.
type NPAPublishersAlertsConfigurationDataSourceModel struct {
	AdminUsers    []types.String `tfsdk:"admin_users"`
	EventTypes    []types.String `tfsdk:"event_types"`
	SelectedUsers types.String   `tfsdk:"selected_users"`
}

// Metadata returns the data source type name.
func (r *NPAPublishersAlertsConfigurationDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_npa_publishers_alerts_configuration"
}

// Schema defines the schema for the data source.
func (r *NPAPublishersAlertsConfigurationDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages the tenant-wide NPA publisher alerts configuration. This is a singleton resource — there is one global alerts policy per tenant, and it applies automatically to all publishers. No per-publisher attachment is required.\n\nUse this resource to configure which admin users receive alert emails, which event types trigger alerts (e.g. CONNECTION_FAILED, UPGRADE_STARTED), and the recipient selection mode.\n",

		Attributes: map[string]schema.Attribute{
			"admin_users": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"event_types": schema.ListAttribute{
				Computed:    true,
				ElementType: types.StringType,
			},
			"selected_users": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

func (r *NPAPublishersAlertsConfigurationDataSource) Configure(ctx context.Context, req datasource.ConfigureRequest, resp *datasource.ConfigureResponse) {
	// Prevent panic if the provider has not been configured.
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*sdk.TerraformProviderNs)

	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected DataSource Configure Type",
			fmt.Sprintf("Expected *sdk.TerraformProviderNs, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)

		return
	}

	r.client = client
}

func (r *NPAPublishersAlertsConfigurationDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data *NPAPublishersAlertsConfigurationDataSourceModel
	var item types.Object

	resp.Diagnostics.Append(req.Config.Get(ctx, &item)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(item.As(ctx, &data, basetypes.ObjectAsOptions{
		UnhandledNullAsEmpty:    true,
		UnhandledUnknownAsEmpty: true,
	})...)

	if resp.Diagnostics.HasError() {
		return
	}

	res, err := r.client.GetNPAPublisherAlerts(ctx)
	if err != nil {
		resp.Diagnostics.AddError("failure to invoke API", err.Error())
		if res != nil && res.RawResponse != nil {
			resp.Diagnostics.AddError("unexpected http request/response", debugResponse(res.RawResponse))
		}
		return
	}
	if res == nil {
		resp.Diagnostics.AddError("unexpected response from API", fmt.Sprintf("%v", res))
		return
	}
	if res.StatusCode != 200 {
		resp.Diagnostics.AddError(fmt.Sprintf("unexpected response from API. Got an unexpected response code %v", res.StatusCode), debugResponse(res.RawResponse))
		return
	}
	if !(res.PublishersAlertGetResponse != nil) {
		resp.Diagnostics.AddError("unexpected response from API. Got an unexpected response body", debugResponse(res.RawResponse))
		return
	}
	resp.Diagnostics.Append(data.RefreshFromSharedPublishersAlertGetResponse(ctx, res.PublishersAlertGetResponse)...)

	if resp.Diagnostics.HasError() {
		return
	}

	// Save updated data into Terraform state
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}
