// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package provider

import "github.com/hashicorp/terraform-plugin-framework/types"

type PrivateAppsGetResponseData struct {
	PrivateApps []types.String `tfsdk:"private_apps"`
}
