// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type AigApplianceImage struct {
	HypervisorPlatform types.String `tfsdk:"hypervisor_platform"`
	Name               types.String `tfsdk:"name"`
}
