// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type DlpActions struct {
	Actions    []Actions    `tfsdk:"actions"`
	DlpProfile types.String `tfsdk:"dlp_profile"`
}
