// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type LbrokerItem struct {
	AccessViaPublicIP   types.String           `tfsdk:"access_via_public_ip"`
	Assessment          *LbrokerItemAssessment `tfsdk:"assessment"`
	CityName            types.String           `tfsdk:"city_name"`
	CommonName          types.String           `tfsdk:"common_name"`
	CountryCode         types.String           `tfsdk:"country_code"`
	CountryName         types.String           `tfsdk:"country_name"`
	CreatedAt           types.String           `tfsdk:"created_at"`
	CustomPrivateIP     types.String           `tfsdk:"custom_private_ip"`
	CustomPublicIP      types.String           `tfsdk:"custom_public_ip"`
	DiscoveredPrivateIP types.String           `tfsdk:"discovered_private_ip"`
	DiscoveredPublicIP  types.String           `tfsdk:"discovered_public_ip"`
	DNSHost             types.String           `tfsdk:"dns_host"`
	GslbUUID            types.String           `tfsdk:"gslb_uuid"`
	HostPort            types.Int32            `tfsdk:"host_port"`
	Latitude            types.Float32          `tfsdk:"latitude"`
	LocalBrokerID       types.Int32            `tfsdk:"local_broker_id"`
	LocalBrokerName     types.String           `tfsdk:"local_broker_name"`
	LocationID          types.String           `tfsdk:"location_id"`
	Longitude           types.Float32          `tfsdk:"longitude"`
	PopName             types.String           `tfsdk:"pop_name"`
	ReachableByClient   types.Bool             `tfsdk:"reachable_by_client"`
	RegionName          types.String           `tfsdk:"region_name"`
	Registered          types.Bool             `tfsdk:"registered"`
	RegisteredAt        types.String           `tfsdk:"registered_at"`
	UpdatedAt           types.String           `tfsdk:"updated_at"`
}
