// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type NpaPolicyResponseItem struct {
	Enabled   types.String       `tfsdk:"enabled"`
	GroupName types.String       `tfsdk:"group_name"`
	ID        types.String       `tfsdk:"id"`
	RuleData  *NpaPolicyRuleData `tfsdk:"rule_data"`
	RuleName  types.String       `tfsdk:"rule_name"`
}
