// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type PortConfig struct {
	Enable types.Bool  `tfsdk:"enable"`
	Port   types.Int64 `tfsdk:"port"`
}
