// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PrivateAppsGetResponse struct {
	Data   *PrivateAppsGetResponseData `tfsdk:"data"`
	Status types.String                `tfsdk:"status"`
	Total  types.Int64                 `tfsdk:"total"`
}
