// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import "github.com/hashicorp/terraform-plugin-framework/types"

type PrivateAppsWithActivities struct {
	Activities []Activities   `tfsdk:"activities"`
	AppID      []types.String `tfsdk:"app_id"`
	AppName    types.String   `tfsdk:"app_name"`
}
