// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package types

import (
	"github.com/hashicorp/terraform-plugin-framework/types"
)

type RbacRoleConfigFunction struct {
	ID           types.Int64                 `tfsdk:"id"`
	Name         types.String                `tfsdk:"name"`
	SubFunctions []RbacRoleConfigSubFunction `tfsdk:"sub_functions"`
}
