// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type DeleteSteeringIpsecTunnelsIDRequest struct {
	// IPSec tunnel id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteSteeringIpsecTunnelsIDRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

// DeleteSteeringIpsecTunnelsIDResponse500ResponseBody - Internal server error
type DeleteSteeringIpsecTunnelsIDResponse500ResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponse500ResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponse500ResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeleteSteeringIpsecTunnelsIDResponse429ResponseBody - Too many requests
type DeleteSteeringIpsecTunnelsIDResponse429ResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponse429ResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponse429ResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeleteSteeringIpsecTunnelsIDResponse405ResponseBody - Method not allowed
type DeleteSteeringIpsecTunnelsIDResponse405ResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponse405ResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponse405ResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeleteSteeringIpsecTunnelsIDResponse404ResponseBody - Not found
type DeleteSteeringIpsecTunnelsIDResponse404ResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponse404ResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponse404ResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeleteSteeringIpsecTunnelsIDResponseResponseBody - Access forbidden
type DeleteSteeringIpsecTunnelsIDResponseResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponseResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponseResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// DeleteSteeringIpsecTunnelsIDResponseBody - Successful operation
type DeleteSteeringIpsecTunnelsIDResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *DeleteSteeringIpsecTunnelsIDResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *DeleteSteeringIpsecTunnelsIDResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type DeleteSteeringIpsecTunnelsIDResponse struct {
	// Successful operation
	TwoHundredApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponseBody
	// Access forbidden
	FourHundredAndThreeApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponseResponseBody
	// Not found
	FourHundredAndFourApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponse404ResponseBody
	// Method not allowed
	FourHundredAndFiveApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponse405ResponseBody
	// Too many requests
	FourHundredAndTwentyNineApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponse429ResponseBody
	// Internal server error
	FiveHundredApplicationJSONObject *DeleteSteeringIpsecTunnelsIDResponse500ResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetTwoHundredApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetFourHundredAndThreeApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndThreeApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetFourHundredAndFourApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponse404ResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFourApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetFourHundredAndFiveApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponse405ResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndFiveApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetFourHundredAndTwentyNineApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponse429ResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredAndTwentyNineApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetFiveHundredApplicationJSONObject() *DeleteSteeringIpsecTunnelsIDResponse500ResponseBody {
	if o == nil {
		return nil
	}
	return o.FiveHundredApplicationJSONObject
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteSteeringIpsecTunnelsIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
