// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/netskope/terraform-provider-ns/internal/sdk/pkg/models/shared"
	"net/http"
)

type GetSteeringIpsecPopsIDRequest struct {
	// Provide comma separated list of fields to be displayed
	Fields *string `queryParam:"style=form,explode=true,name=fields"`
	// POP id
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *GetSteeringIpsecPopsIDRequest) GetFields() *string {
	if o == nil {
		return nil
	}
	return o.Fields
}

func (o *GetSteeringIpsecPopsIDRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type GetSteeringIpsecPopsIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Successful operation
	IpsecPopResponse200 *shared.IpsecPopResponse200
	// Invalid request
	IpsecResponse400 *shared.IpsecResponse400
	// Access forbidden
	IpsecResponse403 *shared.IpsecResponse403
	// Not found
	IpsecResponse404 *shared.IpsecResponse404
	// Method not allowed
	IpsecResponse405 *shared.IpsecResponse405
	// Too many requests
	IpsecResponse429 *shared.IpsecResponse429
	// Internal server error
	IpsecResponse500 *shared.IpsecResponse500
}

func (o *GetSteeringIpsecPopsIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetSteeringIpsecPopsIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetSteeringIpsecPopsIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecPopResponse200() *shared.IpsecPopResponse200 {
	if o == nil {
		return nil
	}
	return o.IpsecPopResponse200
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse400() *shared.IpsecResponse400 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse400
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse403() *shared.IpsecResponse403 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse403
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse404() *shared.IpsecResponse404 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse404
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse405() *shared.IpsecResponse405 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse405
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse429() *shared.IpsecResponse429 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse429
}

func (o *GetSteeringIpsecPopsIDResponse) GetIpsecResponse500() *shared.IpsecResponse500 {
	if o == nil {
		return nil
	}
	return o.IpsecResponse500
}
