// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type Order string

const (
	OrderBefore Order = "before"
	OrderAfter  Order = "after"
)

func (e Order) ToPointer() *Order {
	return &e
}

func (e *Order) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "before":
		fallthrough
	case "after":
		*e = Order(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Order: %v", v)
	}
}

type PatchPolicyNpaPolicygroupsIDGroupOrder struct {
	GroupID *string `json:"group_id,omitempty"`
	Order   *Order  `json:"order,omitempty"`
}

func (o *PatchPolicyNpaPolicygroupsIDGroupOrder) GetGroupID() *string {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *PatchPolicyNpaPolicygroupsIDGroupOrder) GetOrder() *Order {
	if o == nil {
		return nil
	}
	return o.Order
}

type GroupOrder struct {
	GroupOrder *PatchPolicyNpaPolicygroupsIDGroupOrder `json:"group_order,omitempty"`
}

func (o *GroupOrder) GetGroupOrder() *PatchPolicyNpaPolicygroupsIDGroupOrder {
	if o == nil {
		return nil
	}
	return o.GroupOrder
}

type PatchPolicyNpaPolicygroupsIDRequestBody struct {
	GroupName  *string     `json:"group_name,omitempty"`
	GroupOrder *GroupOrder `json:"group_order,omitempty"`
	ModifyBy   *string     `json:"modify_by,omitempty"`
	ModifyType *string     `json:"modify_type,omitempty"`
}

func (o *PatchPolicyNpaPolicygroupsIDRequestBody) GetGroupName() *string {
	if o == nil {
		return nil
	}
	return o.GroupName
}

func (o *PatchPolicyNpaPolicygroupsIDRequestBody) GetGroupOrder() *GroupOrder {
	if o == nil {
		return nil
	}
	return o.GroupOrder
}

func (o *PatchPolicyNpaPolicygroupsIDRequestBody) GetModifyBy() *string {
	if o == nil {
		return nil
	}
	return o.ModifyBy
}

func (o *PatchPolicyNpaPolicygroupsIDRequestBody) GetModifyType() *string {
	if o == nil {
		return nil
	}
	return o.ModifyType
}

// QueryParamSilent - flag to skip output except status code
type QueryParamSilent string

const (
	QueryParamSilentOne  QueryParamSilent = "1"
	QueryParamSilentZero QueryParamSilent = "0"
)

func (e QueryParamSilent) ToPointer() *QueryParamSilent {
	return &e
}

func (e *QueryParamSilent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "0":
		*e = QueryParamSilent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for QueryParamSilent: %v", v)
	}
}

type PatchPolicyNpaPolicygroupsIDRequest struct {
	RequestBody PatchPolicyNpaPolicygroupsIDRequestBody `request:"mediaType=application/json"`
	// policy group rule id
	ID int64 `pathParam:"style=simple,explode=false,name=id"`
	// flag to skip output except status code
	Silent *QueryParamSilent `queryParam:"style=form,explode=true,name=silent"`
}

func (o *PatchPolicyNpaPolicygroupsIDRequest) GetRequestBody() PatchPolicyNpaPolicygroupsIDRequestBody {
	if o == nil {
		return PatchPolicyNpaPolicygroupsIDRequestBody{}
	}
	return o.RequestBody
}

func (o *PatchPolicyNpaPolicygroupsIDRequest) GetID() int64 {
	if o == nil {
		return 0
	}
	return o.ID
}

func (o *PatchPolicyNpaPolicygroupsIDRequest) GetSilent() *QueryParamSilent {
	if o == nil {
		return nil
	}
	return o.Silent
}

// PatchPolicyNpaPolicygroupsIDResponseResponseBody - Invalid request
type PatchPolicyNpaPolicygroupsIDResponseResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *PatchPolicyNpaPolicygroupsIDResponseResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *PatchPolicyNpaPolicygroupsIDResponseResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

// PatchPolicyNpaPolicygroupsIDResponseBody - successful operation
type PatchPolicyNpaPolicygroupsIDResponseBody struct {
	CanBeEditedDeleted *int64  `json:"can_be_edited_deleted,omitempty"`
	GroupID            *int64  `json:"group_id,omitempty"`
	GroupName          *string `json:"group_name,omitempty"`
	GroupPinnedID      *int64  `json:"group_pinned_id,omitempty"`
	GroupProdID        *int64  `json:"group_prod_id,omitempty"`
	GroupType          *int64  `json:"group_type,omitempty"`
	ModifyTime         *string `json:"modify_time,omitempty"`
	ModifyType         *string `json:"modify_type,omitempty"`
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetCanBeEditedDeleted() *int64 {
	if o == nil {
		return nil
	}
	return o.CanBeEditedDeleted
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetGroupID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetGroupName() *string {
	if o == nil {
		return nil
	}
	return o.GroupName
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetGroupPinnedID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupPinnedID
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetGroupProdID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupProdID
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetGroupType() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupType
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetModifyTime() *string {
	if o == nil {
		return nil
	}
	return o.ModifyTime
}

func (o *PatchPolicyNpaPolicygroupsIDResponseBody) GetModifyType() *string {
	if o == nil {
		return nil
	}
	return o.ModifyType
}

type PatchPolicyNpaPolicygroupsIDResponse struct {
	// successful operation
	TwoHundredApplicationJSONObject *PatchPolicyNpaPolicygroupsIDResponseBody
	// Invalid request
	FourHundredApplicationJSONObject *PatchPolicyNpaPolicygroupsIDResponseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PatchPolicyNpaPolicygroupsIDResponse) GetTwoHundredApplicationJSONObject() *PatchPolicyNpaPolicygroupsIDResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PatchPolicyNpaPolicygroupsIDResponse) GetFourHundredApplicationJSONObject() *PatchPolicyNpaPolicygroupsIDResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *PatchPolicyNpaPolicygroupsIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PatchPolicyNpaPolicygroupsIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PatchPolicyNpaPolicygroupsIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
