// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type PostPolicyNpaPolicygroupsOrder string

const (
	PostPolicyNpaPolicygroupsOrderBefore PostPolicyNpaPolicygroupsOrder = "before"
	PostPolicyNpaPolicygroupsOrderAfter  PostPolicyNpaPolicygroupsOrder = "after"
)

func (e PostPolicyNpaPolicygroupsOrder) ToPointer() *PostPolicyNpaPolicygroupsOrder {
	return &e
}

func (e *PostPolicyNpaPolicygroupsOrder) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "before":
		fallthrough
	case "after":
		*e = PostPolicyNpaPolicygroupsOrder(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostPolicyNpaPolicygroupsOrder: %v", v)
	}
}

type PostPolicyNpaPolicygroupsGroupOrder struct {
	GroupID string                         `json:"group_id"`
	Order   PostPolicyNpaPolicygroupsOrder `json:"order"`
}

func (o *PostPolicyNpaPolicygroupsGroupOrder) GetGroupID() string {
	if o == nil {
		return ""
	}
	return o.GroupID
}

func (o *PostPolicyNpaPolicygroupsGroupOrder) GetOrder() PostPolicyNpaPolicygroupsOrder {
	if o == nil {
		return PostPolicyNpaPolicygroupsOrder("")
	}
	return o.Order
}

type PostPolicyNpaPolicygroupsRequestBody struct {
	GroupName  string                              `json:"group_name"`
	GroupOrder PostPolicyNpaPolicygroupsGroupOrder `json:"group_order"`
}

func (o *PostPolicyNpaPolicygroupsRequestBody) GetGroupName() string {
	if o == nil {
		return ""
	}
	return o.GroupName
}

func (o *PostPolicyNpaPolicygroupsRequestBody) GetGroupOrder() PostPolicyNpaPolicygroupsGroupOrder {
	if o == nil {
		return PostPolicyNpaPolicygroupsGroupOrder{}
	}
	return o.GroupOrder
}

// PostPolicyNpaPolicygroupsQueryParamSilent - flag to skip output except status code
type PostPolicyNpaPolicygroupsQueryParamSilent string

const (
	PostPolicyNpaPolicygroupsQueryParamSilentOne  PostPolicyNpaPolicygroupsQueryParamSilent = "1"
	PostPolicyNpaPolicygroupsQueryParamSilentZero PostPolicyNpaPolicygroupsQueryParamSilent = "0"
)

func (e PostPolicyNpaPolicygroupsQueryParamSilent) ToPointer() *PostPolicyNpaPolicygroupsQueryParamSilent {
	return &e
}

func (e *PostPolicyNpaPolicygroupsQueryParamSilent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "0":
		*e = PostPolicyNpaPolicygroupsQueryParamSilent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostPolicyNpaPolicygroupsQueryParamSilent: %v", v)
	}
}

type PostPolicyNpaPolicygroupsRequest struct {
	RequestBody PostPolicyNpaPolicygroupsRequestBody `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *PostPolicyNpaPolicygroupsQueryParamSilent `queryParam:"style=form,explode=true,name=silent"`
}

func (o *PostPolicyNpaPolicygroupsRequest) GetRequestBody() PostPolicyNpaPolicygroupsRequestBody {
	if o == nil {
		return PostPolicyNpaPolicygroupsRequestBody{}
	}
	return o.RequestBody
}

func (o *PostPolicyNpaPolicygroupsRequest) GetSilent() *PostPolicyNpaPolicygroupsQueryParamSilent {
	if o == nil {
		return nil
	}
	return o.Silent
}

// PostPolicyNpaPolicygroupsResponseResponseBody - Invalid request
type PostPolicyNpaPolicygroupsResponseResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *PostPolicyNpaPolicygroupsResponseResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *PostPolicyNpaPolicygroupsResponseResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type PostPolicyNpaPolicygroupsData struct {
	CanBeEditedDeleted *string `json:"can_be_edited_deleted,omitempty"`
	GroupID            *string `json:"group_id,omitempty"`
	GroupName          *string `json:"group_name,omitempty"`
	GroupPinnedID      *int64  `json:"group_pinned_id,omitempty"`
	GroupProdID        *int64  `json:"group_prod_id,omitempty"`
	GroupType          *string `json:"group_type,omitempty"`
	ModifyTime         *string `json:"modify_time,omitempty"`
	ModifyType         *string `json:"modify_type,omitempty"`
}

func (o *PostPolicyNpaPolicygroupsData) GetCanBeEditedDeleted() *string {
	if o == nil {
		return nil
	}
	return o.CanBeEditedDeleted
}

func (o *PostPolicyNpaPolicygroupsData) GetGroupID() *string {
	if o == nil {
		return nil
	}
	return o.GroupID
}

func (o *PostPolicyNpaPolicygroupsData) GetGroupName() *string {
	if o == nil {
		return nil
	}
	return o.GroupName
}

func (o *PostPolicyNpaPolicygroupsData) GetGroupPinnedID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupPinnedID
}

func (o *PostPolicyNpaPolicygroupsData) GetGroupProdID() *int64 {
	if o == nil {
		return nil
	}
	return o.GroupProdID
}

func (o *PostPolicyNpaPolicygroupsData) GetGroupType() *string {
	if o == nil {
		return nil
	}
	return o.GroupType
}

func (o *PostPolicyNpaPolicygroupsData) GetModifyTime() *string {
	if o == nil {
		return nil
	}
	return o.ModifyTime
}

func (o *PostPolicyNpaPolicygroupsData) GetModifyType() *string {
	if o == nil {
		return nil
	}
	return o.ModifyType
}

// PostPolicyNpaPolicygroupsResponseBody - successful operation
type PostPolicyNpaPolicygroupsResponseBody struct {
	Data *PostPolicyNpaPolicygroupsData `json:"data,omitempty"`
}

func (o *PostPolicyNpaPolicygroupsResponseBody) GetData() *PostPolicyNpaPolicygroupsData {
	if o == nil {
		return nil
	}
	return o.Data
}

type PostPolicyNpaPolicygroupsResponse struct {
	// successful operation
	TwoHundredApplicationJSONObject *PostPolicyNpaPolicygroupsResponseBody
	// Invalid request
	FourHundredApplicationJSONObject *PostPolicyNpaPolicygroupsResponseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostPolicyNpaPolicygroupsResponse) GetTwoHundredApplicationJSONObject() *PostPolicyNpaPolicygroupsResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostPolicyNpaPolicygroupsResponse) GetFourHundredApplicationJSONObject() *PostPolicyNpaPolicygroupsResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *PostPolicyNpaPolicygroupsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostPolicyNpaPolicygroupsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostPolicyNpaPolicygroupsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
