// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type PostSteeringAppsPrivateTagsPublisherTags struct {
	TagID   *int    `json:"tag_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsPublisherTags) GetTagID() *int {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *PostSteeringAppsPrivateTagsPublisherTags) GetTagName() *string {
	if o == nil {
		return nil
	}
	return o.TagName
}

type PostSteeringAppsPrivateTagsTags struct {
	TagID   *int    `json:"tag_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsTags) GetTagID() *int {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *PostSteeringAppsPrivateTagsTags) GetTagName() *string {
	if o == nil {
		return nil
	}
	return o.TagName
}

type PostSteeringAppsPrivateTagsRequestBody struct {
	ID            *string                                    `json:"id,omitempty"`
	Ids           []string                                   `json:"ids,omitempty"`
	PublisherTags []PostSteeringAppsPrivateTagsPublisherTags `json:"publisher_tags,omitempty"`
	Tags          []PostSteeringAppsPrivateTagsTags          `json:"tags,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsRequestBody) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *PostSteeringAppsPrivateTagsRequestBody) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}

func (o *PostSteeringAppsPrivateTagsRequestBody) GetPublisherTags() []PostSteeringAppsPrivateTagsPublisherTags {
	if o == nil {
		return nil
	}
	return o.PublisherTags
}

func (o *PostSteeringAppsPrivateTagsRequestBody) GetTags() []PostSteeringAppsPrivateTagsTags {
	if o == nil {
		return nil
	}
	return o.Tags
}

// PostSteeringAppsPrivateTagsResponseResponseBody - Invalid request
type PostSteeringAppsPrivateTagsResponseResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsResponseResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *PostSteeringAppsPrivateTagsResponseResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type PostSteeringAppsPrivateTagsData struct {
	TagID   *int    `json:"tag_id,omitempty"`
	TagName *string `json:"tag_name,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsData) GetTagID() *int {
	if o == nil {
		return nil
	}
	return o.TagID
}

func (o *PostSteeringAppsPrivateTagsData) GetTagName() *string {
	if o == nil {
		return nil
	}
	return o.TagName
}

type PostSteeringAppsPrivateTagsStatus string

const (
	PostSteeringAppsPrivateTagsStatusSuccess  PostSteeringAppsPrivateTagsStatus = "success"
	PostSteeringAppsPrivateTagsStatusNotFound PostSteeringAppsPrivateTagsStatus = "not found"
)

func (e PostSteeringAppsPrivateTagsStatus) ToPointer() *PostSteeringAppsPrivateTagsStatus {
	return &e
}

func (e *PostSteeringAppsPrivateTagsStatus) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "success":
		fallthrough
	case "not found":
		*e = PostSteeringAppsPrivateTagsStatus(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PostSteeringAppsPrivateTagsStatus: %v", v)
	}
}

// PostSteeringAppsPrivateTagsResponseBody - successful operation
type PostSteeringAppsPrivateTagsResponseBody struct {
	Data   []PostSteeringAppsPrivateTagsData  `json:"data,omitempty"`
	Status *PostSteeringAppsPrivateTagsStatus `json:"status,omitempty"`
}

func (o *PostSteeringAppsPrivateTagsResponseBody) GetData() []PostSteeringAppsPrivateTagsData {
	if o == nil {
		return nil
	}
	return o.Data
}

func (o *PostSteeringAppsPrivateTagsResponseBody) GetStatus() *PostSteeringAppsPrivateTagsStatus {
	if o == nil {
		return nil
	}
	return o.Status
}

type PostSteeringAppsPrivateTagsResponse struct {
	// successful operation
	TwoHundredApplicationJSONObject *PostSteeringAppsPrivateTagsResponseBody
	// Invalid request
	FourHundredApplicationJSONObject *PostSteeringAppsPrivateTagsResponseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostSteeringAppsPrivateTagsResponse) GetTwoHundredApplicationJSONObject() *PostSteeringAppsPrivateTagsResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostSteeringAppsPrivateTagsResponse) GetFourHundredApplicationJSONObject() *PostSteeringAppsPrivateTagsResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *PostSteeringAppsPrivateTagsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSteeringAppsPrivateTagsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSteeringAppsPrivateTagsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
