// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
)

type PostSteeringAppsPrivateGetpolicyinuseRequestBody struct {
	Ids []string `json:"ids,omitempty"`
}

func (o *PostSteeringAppsPrivateGetpolicyinuseRequestBody) GetIds() []string {
	if o == nil {
		return nil
	}
	return o.Ids
}

// PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody - Invalid request
type PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody struct {
	Result *string `json:"result,omitempty"`
	Status *int64  `json:"status,omitempty"`
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody) GetResult() *string {
	if o == nil {
		return nil
	}
	return o.Result
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody) GetStatus() *int64 {
	if o == nil {
		return nil
	}
	return o.Status
}

type PostSteeringAppsPrivateGetpolicyinuseData struct {
	Token *string `json:"token,omitempty"`
}

func (o *PostSteeringAppsPrivateGetpolicyinuseData) GetToken() *string {
	if o == nil {
		return nil
	}
	return o.Token
}

// PostSteeringAppsPrivateGetpolicyinuseResponseBody - successful operation
type PostSteeringAppsPrivateGetpolicyinuseResponseBody struct {
	Data []PostSteeringAppsPrivateGetpolicyinuseData `json:"data,omitempty"`
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponseBody) GetData() []PostSteeringAppsPrivateGetpolicyinuseData {
	if o == nil {
		return nil
	}
	return o.Data
}

type PostSteeringAppsPrivateGetpolicyinuseResponse struct {
	// successful operation
	TwoHundredApplicationJSONObject *PostSteeringAppsPrivateGetpolicyinuseResponseBody
	// Invalid request
	FourHundredApplicationJSONObject *PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponse) GetTwoHundredApplicationJSONObject() *PostSteeringAppsPrivateGetpolicyinuseResponseBody {
	if o == nil {
		return nil
	}
	return o.TwoHundredApplicationJSONObject
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponse) GetFourHundredApplicationJSONObject() *PostSteeringAppsPrivateGetpolicyinuseResponseResponseBody {
	if o == nil {
		return nil
	}
	return o.FourHundredApplicationJSONObject
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PostSteeringAppsPrivateGetpolicyinuseResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
