// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"encoding/json"
	"fmt"
	"github.com/netskope/terraform-provider-ns/internal/sdk/pkg/models/shared"
	"net/http"
)

// PutSteeringAppsPrivatePrivateAppIDQueryParamSilent - flag to skip output except status code
type PutSteeringAppsPrivatePrivateAppIDQueryParamSilent string

const (
	PutSteeringAppsPrivatePrivateAppIDQueryParamSilentOne  PutSteeringAppsPrivatePrivateAppIDQueryParamSilent = "1"
	PutSteeringAppsPrivatePrivateAppIDQueryParamSilentZero PutSteeringAppsPrivatePrivateAppIDQueryParamSilent = "0"
)

func (e PutSteeringAppsPrivatePrivateAppIDQueryParamSilent) ToPointer() *PutSteeringAppsPrivatePrivateAppIDQueryParamSilent {
	return &e
}

func (e *PutSteeringAppsPrivatePrivateAppIDQueryParamSilent) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "1":
		fallthrough
	case "0":
		*e = PutSteeringAppsPrivatePrivateAppIDQueryParamSilent(v)
		return nil
	default:
		return fmt.Errorf("invalid value for PutSteeringAppsPrivatePrivateAppIDQueryParamSilent: %v", v)
	}
}

type PutSteeringAppsPrivatePrivateAppIDRequest struct {
	// private apps id
	PrivateAppID          int                          `pathParam:"style=simple,explode=false,name=private_app_id"`
	PrivateAppsPutRequest shared.PrivateAppsPutRequest `request:"mediaType=application/json"`
	// flag to skip output except status code
	Silent *PutSteeringAppsPrivatePrivateAppIDQueryParamSilent `queryParam:"style=form,explode=true,name=silent"`
}

func (o *PutSteeringAppsPrivatePrivateAppIDRequest) GetPrivateAppID() int {
	if o == nil {
		return 0
	}
	return o.PrivateAppID
}

func (o *PutSteeringAppsPrivatePrivateAppIDRequest) GetPrivateAppsPutRequest() shared.PrivateAppsPutRequest {
	if o == nil {
		return shared.PrivateAppsPutRequest{}
	}
	return o.PrivateAppsPutRequest
}

func (o *PutSteeringAppsPrivatePrivateAppIDRequest) GetSilent() *PutSteeringAppsPrivatePrivateAppIDQueryParamSilent {
	if o == nil {
		return nil
	}
	return o.Silent
}

type PutSteeringAppsPrivatePrivateAppIDResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// successful operation
	PrivateAppsResponse *shared.PrivateAppsResponse
	// Invalid request
	PrivateAppsResponse400 *shared.PrivateAppsResponse400
}

func (o *PutSteeringAppsPrivatePrivateAppIDResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *PutSteeringAppsPrivatePrivateAppIDResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *PutSteeringAppsPrivatePrivateAppIDResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *PutSteeringAppsPrivatePrivateAppIDResponse) GetPrivateAppsResponse() *shared.PrivateAppsResponse {
	if o == nil {
		return nil
	}
	return o.PrivateAppsResponse
}

func (o *PutSteeringAppsPrivatePrivateAppIDResponse) GetPrivateAppsResponse400() *shared.PrivateAppsResponse400 {
	if o == nil {
		return nil
	}
	return o.PrivateAppsResponse400
}
